### ISSUE TITLE
Request Account on wiki fails with "Incorrect or missing confirmation code."

### ISSUE THREAD

**Issue by jerrac** [openwebwork/webwork2#1006]
This seems like it should be reported elsewhere, but I really couldn't find a better place... Sorry about that.

For the past couple weeks I've been trying to register an account on the wiki (http://webwork.maa.org/wiki/Special:RequestAccount) so that I can post in the community forum.

Every time I submit the form, I get an "Incorrect or missing confirmation code." error. 

This is in both Firefox and Chromium. Chromium doesn't even have any extensions installed.

It isn't referring to the sum robot check, is it? I know I've entered the correct answer there.

Am I missing something?

Thanks.

**Comment by mgage** [comment]
Hi David,

That captcha sometimes causes troubles — I have been unable to determine what causes it to fail consistently for certain people.


(hence the note to email gage@math.rochester.edu<mailto:gage@math.rochester.edu> if things aren’t working)

Send me a note at gage@math.rochester.edu<mailto:gage@math.rochester.edu> with your email address and I’ll create an account for DavidReagan and
send you a password via email.


Sorry for the hassle.

Take care,

Mike






On Sep 11, 2019, at 1:16 PM, David Reagan <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems like it should be reported elsewhere, but I really couldn't find a better place... Sorry about that.

For the past couple weeks I've been trying to register an account on the wiki (http://webwork.maa.org/wiki/Special:RequestAccount<https://urldefense.proofpoint.com/v2/url?u=http-3A__webwork.maa.org_wiki_Special-3ARequestAccount&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=C6Pt5AGtImanmAdcooarL-JZO8M5dSFPfs3VweYXYkE&m=nUcR6SPRsNkTsAvClmJ2v_Q1Nlq168OSW0wMS9Mjhdo&s=4TKt1eT1SxWImgTVhWQsi_wbAE16NJRa6-GOyo8sz28&e=>) so that I can post in the community forum.

Every time I submit the form, I get an "Incorrect or missing confirmation code." error.

This is in both Firefox and Chromium. Chromium doesn't even have any extensions installed.

It isn't referring to the sum robot check, is it? I know I've entered the correct answer there.

Am I missing something?

Thanks.

**Comment by jerrac** [comment]
Since I got in, I'll go ahead and close this.
