### ISSUE TITLE
FileManager - Give better response if a download of more than one file is requested

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1022]
If I select multiple files and click Download in the FileManager, the displayed page looks unusual (layout messed up) and the warnings are not particularly helpful. Giving a nicer error message and a regularly formatted page would be nice.

```
WeBWorK Warnings
WeBWorK has encountered warnings while processing your request. If this occured when viewing a problem, it was likely caused by an error or ambiguity in that problem. Otherwise, it may indicate a problem with the WeBWorK system itself. If you are a student, report these warnings to your professor to have them corrected. If you are a professor, please consult the warning output below for more information.

Warning messages
Use of uninitialized value $pwd in string eq at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/FileManager.pm line 246.
Use of uninitialized value $pwd in string eq at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/FileManager.pm line 246.
Use of uninitialized value $dir in substitution (s///) at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/FileManager.pm line 1032.
Use of uninitialized value $dir in split at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/FileManager.pm line 1033.
Use of uninitialized value $root in concatenation (.) or string at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/FileManager.pm line 1052.
Use of uninitialized value $pwd in concatenation (.) or string at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Instructor/FileManager.pm line 1052.
Request information
Time	Thu Sep 26 13:15:35 2019
Method	POST
URI	/webwork2/spring17mth164/instructor/file_manager/
```
followed by
```
You can only download one file at a time.
```

**Comment by mgage** [comment]
These are only "undefined" warning messages (the last message is the real one).   It's probably safe to use  the construction $foobar//'';        to uniformly make sure that every value is defined.

**Comment by drgrice1** [comment]
It seems that it would be nice to update this to create a zip file (or tar ball) and offer that for download in the event that multiple files are selected.  Of course that takes some work to implement.

In any case the warnings and the garbled result should be fixed for now!

**Comment by dpvc** [comment]
The problem turns out to be due to incorrectly localizing the `$action` variable in the `getFile()` method.  The action passed to `getFile()` is not from the UI, and so doesn't need to be localized.  The change to a capitalized `$action` when the action passed to it is always lower-case caused the test for whether the action is a download action to fail, and the `Refresh()` method was being called incorrectly.

I've submitted a PR to fix the issue.

Whether it should make an archive of the files is a question for another time.  (There is a "Make Archive" button that could be used to do that, and then download that, though it is a multi-step process.)

**Comment by mgage** [comment]
Thanks Davide.  I’ve merged the PR.

I agree that method to collect and compress an archive and download to the desktop in one step would be a good addition (and mirrors the automatic upload and
unpack feature).  I also agree it is for another time.  In addition I would like the ability to handle  files of type   .zip, .tar.gz and  .tgz either automatically or by
setting a configuration.

One goal for the next release (or the one after?) would be to make it easy for an instructor to select a working homework set and download an archive
containing the set definition file, any local pg files not in the OPL, and any auxiliary files which could then be emailed to a colleague who could upload
them automatically in their course. It would make it easier to share homework and eventually complete courses.

We’re converging on release 2.15.

Thanks again.

Take care,

Mike



On Sep 27, 2019, at 7:04 AM, Davide P. Cervone <notifications@github.com<mailto:notifications@github.com>> wrote:


The problem turns out to be due to incorrectly localizing the $action variable in the getFile() method. The action passed to getFile() is not from the UI, and so doesn't need to be localized. The change to a capitalized $action when the action passed to it is always lower-case caused the test for whether the action is a download action to fail, and the Refresh() method was being called incorrectly.

I've submitted a PR to fix the issue.

Whether it should make an archive of the files is a question for another time. (There is a "Make Archive" button that could be used to do that, and then download that, though it is a multi-step process.)
