### ISSUE TITLE
MathQuill and space characters

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1067]
MathQuill kills space characters. But is there any reason it has to do this? Could it be engineered to preserve them? (Possibly collapsing more than one space down to one?)

A few situations where you want the space to stay:

1. The context is a mixed number fraction problem, and the student is trying to answer `1 2/3`.
1. The answer is a multi-word string, like `no real solution`.

I understand that text mode can be used to force a space character. While that is logical for item 2, it is not logical for item 1. Either way, trying to explain about how and when to use text mode to students is a challenge.

My thinking is, why is there a need to kill the spaces in the first place?

**Comment by drgrice1** [comment]
It was Andrew's decision primarily to utilize the MathQuill option, spaceBehavesLikeTab.  I think the primary reason was that of convenience.  That option makes it so that if you press space after typing a fraction then it leaves the denominator, if you type space after typing the contents of a radical it leaves the radical, if you type space after typing an exponent it leaves the exponent, etc.  Of course the tab button also does that, but space is easier to reach on the keyboard.

Andrew may have other motivations for wanting the option also.

Note that there is a WeBWorK cmp option that you can use to turn of the spaceBehavesLikeTab option for an answer rule.  Add `mathQuillOpts => 'spaceBehavesLikeTab: false'` to the cmp method for that answer.

Now, as to your first case.  That will still not work the way that you expect even if the spaceBehavesLikeTab option is disabled.  If one types `1 2/3` in a MathQuill answer box then the string that will be passed to WeBWorK will be `1 ((2)/(3))`, which WeBWorK will interpret as the product of 1 and 2/3.  Those extra parentheses are needed for the string sent to WeBWorK to be parsed into what is visually displayed.  The case of mixed numbers is the one exception.  I have done some work on making an option for MathQuill that removes those extra parentheses in that case.  I want it to be an option that is added to any answer that allows mixed numbers automatically, but I don't have it all figured out yet.  I have the MathQuill implementation figured out to utilize the option, and I could put that in, and then you would have to add the option to the mathQuillOpts flag manually for now.

**Comment by Alex-Jordan** [comment]
> Note that there is a WeBWorK cmp option that you can use to turn off the spaceBehavesLikeTab option for an answer rule. Add mathQuillOpts => 'spaceBehavesLikeTab: false' to the cmp method for that answer.

Hmm, I feel like it is a bad idea to start mixing this kind of thing (something about how the WW front end should behave) into the code for individual problems. (I've long felt the same way about `$showHint`, `$refreshCachedImages`, etc.) If it were something more semantic like `expectStudentsToAnswerWithStrings => 1`, that would be different.  In any case, I don't want to do edit the hundreds of problems that would need it right now, not to mention tracking down all the forking of the problems that I can't even see.

No need to rush this, at least not for us here. We're just going to turn off MathQuill in most courses this term. I think I mentioned it a good while back in one of the MathQuill discussion threads, but I think we could make answer blanks automatically carry some information about what kind of answer is expected. Then maybe MathQuill could respond to that. I'd be more interested in that approach then something where problem authors have to set flags.

Crude outline of one possible plan:

1. MathQuill is only available when it's a PGML problem with answer blank syntax like `[_]{$ans}`. Because that binds the answer to the answer blank at the point where the answer blank is being written, and the code in PGML can recognize this. Other methods make an answer blank and then at an unknown place later in the problem code, they associate the answer with that answer blank.

1. It is further only available when the answer is a MathObject, so we can access the hash of all sorts of information about `$ans`.

1. Use hash keys in certain MathObject constructions that convey features about how this kind of answer might be entered by a student, without giving away too much. (And where needed, create new hash keys for certain MathObjects.) For example, if the answer itself is a string (but also considering the effect of `typeMatch` if present) then the answer blank has something like `data-expectString="1"`. Or if the answer is a Fraction object and the flags are set so that a student might be entering a mixed number, indicate that. Or if the answer is a NumberWithUnits, indicate that, and maybe MathQuill could pre-parse what is entered into two parts.

There's probably problems with the above, but it's the basic outline of what I was thinking before.

**Comment by drgrice1** [comment]
> Hmm, I feel like it is a bad idea to start mixing this kind of thing (something about how the WW front end should behave) into the code for individual problems. (I've long felt the same way about `$showHint`, `$refreshCachedImages`, etc.) If it were something more semantic like `expectStudentsToAnswerWithStrings => 1`, that would be different.

I think that $showHint maybe should be a course configuration option and is a question of WW front end behavior, but I don't agree with $refreshCachedImages (and I don't know about etc.).  Whether or not an image should be regenerated depends on if it needs to be regenerated due to being a dynamic image or a static image or other considerations and is not a WW front end behavior issue.  For MathQuill answer boxes and how the string is sent to WW will also be something for the author (or context or answer type) to consider, and is not something that makes sense to have as a course configuration option and is also not a WW front end behavior issue.

> I think we could make answer blanks automatically carry some information about what kind of answer is expected. Then maybe MathQuill could respond to that. I'd be more interested in that approach than something where problem authors have to set flags.

I agree that MathQuill behavior should key in on the type of answer.  I think that context flags and cmp options that are automatically added to certain types of answers is the way to go for this.  Perhaps a flag like `expectStudentsToAnswerWithStrings => 1` as you suggest above would make sense for some situations, but I also don't want to get carried away with hundreds of flags introduced.  The mathQuillOpts cmp flag is a single flag that allows the problem author (or even better a context or particular answer type) to override all MathQuill options (excepting certain event handlers).

I don't think that your outline below is particularly well thought out in terms of feasibility as well as sensible behavior.

> Crude outline of one possible plan:
> 
>     1. MathQuill is only available when it's a PGML problem with answer blank syntax like `[_]{$ans}`. Because that binds the answer to the answer blank at the point where the answer blank is being written, and the code in PGML can recognize this. Other methods make an answer blank and then at an unknown place later in the problem code, they associate the answer with that answer blank.

This is, to be frank, a very bad idea.  To say that MathQuill answers boxes will only work with a very specially set up PGML problem and not a general PG problem is counter-intuitive.  General instructors working from problems in the OPL will not even know how a problem is encoded, and when they select the option to use MathQuill they won't understand why it is enabled on some problems and not on others.

>     2. It is further only available when the answer is a MathObject, so we can access the hash of all sorts of information about `$ans`.

This follows the same counter-intuitive line as your first step in this plan of action.

Generally, I think the best way to proceed is as DPVC suggested at one point in the initial pull request for the MathQuill answer boxes and utilize the context and flags therein for particular types of answers.

**Comment by drdrew42** [comment]
Sorry I'm jumping in late here, but to answer the original question - MathQuill is originally designed to turn typed, in-line mathematics into LaTeX code, and LaTeX predominantly ignores spaces and instead relies on specific code to generate whitespace. Furthermore, strings of alphabetic characters are primarily interpreted by MathQuill as variables - unless they appear in a particular configuration (such as 'abs', 'sqrt', 'cos', etc...) wherein they they are captured and translated into the corresponding function/category. So, for any other string of uninterrupted alphabetical characters, the individual characters are all smashed together into what MathQuill sees as a long product of variables. 

As to the choice for using spaceBehavesLikeTab, it was primarily based around mobile-device users who would not have an accessible 'tab' button (or arrows, or other means by which to exit fractions or exponents). These users would have to manually reposition the cursor each time they needed to leave a fraction or exponent without this particular configuration.

As Glenn points out, regardless of this space/tab setting - MathQuill will still eat your whitespace in math-mode because that is what LaTeX does, and MathQuill is still, fundamentally, a LaTeX-focused interpreter.

Now, if Glenn has alterations to MathQuill that will allow for an effective toggle between these two fractional interpretations, it raises a new possible avenue (for MathObject problems only): **can we equip contexts to automatically incorporate these context-specific MathQuill flags when the problem is rendered?**

Could this be accomplished by pushing the relevant `mathQuillOpts` string(s) into the default cmp options whenever certain context objects are paired with an answer blank? `[_]{$ans}` or `\{$ans->ans_rule\}`

**Comment by Alex-Jordan** [comment]
At the risk of derailing the thread, 

> Whether or not an image should be regenerated depends on if it needs to be regenerated due to being a dynamic image or a static image or other considerations

is making my point better than I could. Ideally the image should have an attribute/property that indicates it is dynamic/static. That's the thing that is intrinsic to the problem. (Really, to the image within the problem, even better.) The setting of that property could be automated in some scenarios, explicitly set by the author in others.

If the author is thinking about `refreshCachedImages` they are thinking two steps down the line in the narrower context of WW HTML output.  They should be free from thinking too much about the output mode (unless they keep the problem to themselves and don't share with the OPL or others). The system could deduce whether to refresh based on the appropriate image properties (including file size).

Particularly with refreshing cached images, the need for this must be so much smaller since the days when `refreshCachedImages` was created. That's another thing that could be adjusted globally...if it hasn't been hard coded into ten thousand problems.

> For MathQuill answer boxes and how the string is sent to WW will also be something for the author (or context or answer type) to consider, and is not something that makes sense to have as a course configuration option and is also not a WW front end behavior issue.

I just disagree with this. Using MathQuill at all is specific to using the HTML output mode. If the author has to think about this to use it in the right way, then it can't be used right on the tens of thousands of existing problems. And it will end up being misused on forks and descendants of problems. I believe there are ways for a MathObject to "know" how to use it well, and we could automate that.

About my bad idea. The point is that many problems use `\{ans_rule()\}` early in the problem, and that builds the HTML input field with its HTML `id`. I'm assuming this input element is where `data-` attributes would go that MathQuill could respond to. Later in the PG code, these problems use `ANS` to attach an cmp routine, which can know things about the answer, but the problem is at this point it can't go back and rewrite that HTML input element and give it `data-` attributes. This is my working understanding of how input fields and cmp routines are connected, which I admit I haven't researched in a long time.

When you use PGML's `[_]{$ans}` then PGML.pl gives you the opportunity to know things about the answer at the same time you will go build the HTML input field. Even using `$ans->ans_rule` when `$ans` is a MathObject is, I think, not giving you this. I think that as currently implemented, that usually calls some more basic answer rule constructor without passing the MathObject itself. (If that much is true, it could be changed.) PGML with a MathObject is the one scenario where I can see the two things being tied together already.

I think it is fine to leave an option to just "turn on" MathQuill all the time, as it is right now. But it's useless to us here that way, because it makes many problems unusable. We just had to shut it off. Not just with issues that have been mentioned, but weird ones like problems where we have answers like `1<2<5/2<13/5<3` get parentheses weird places as you might imagine, ultimately because of those fractions. I'd like to work toward an additional option that shuts down MathQuill completely and selectively green lights conditions where it is OK. And I don't think people will care that some answer blanks have it and other don't. (I already see that behavior in some commercial systems.)

**Comment by drgrice1** [comment]
> > Whether or not an image should be regenerated depends on if it needs to be regenerated due to being a dynamic image or a static image or other considerations
>
> is making my point better than I could. Ideally the image should have an attribute/property that indicates it is dynamic/static. That's the thing that is intrinsic to the problem. (Really, to the image within the problem, even better.) The setting of that property could be automated in some scenarios, explicitly set by the author in others.
>
> If the author is thinking about `refreshCachedImages` they are thinking two steps down the line in the narrower context of WW HTML output. They should be free from thinking too much about the output mode (unless they keep the problem to themselves and don't share with the OPL or others). The system could deduce whether to refresh based on the appropriate image properties (including file size).

It seems that it is not the options that you disagree with, but rather that the author needs to put them in, and that they are not automatically put in.  On that I agree.

> > For MathQuill answer boxes and how the string is sent to WW will also be something for the author (or context or answer type) to consider, and is not something that makes sense to have as a course configuration option and is also not a WW front end behavior issue.
> 
> I just disagree with this.

I don't think you do disagree. You seem to be ignoring my parenthetical comment which is what you basically expressed here, and is the same point as above.   That being that the options that modify behavior should automatically be applied as needed.  In all of these cases, it is really just a matter of implementation that is needed.

> About my bad idea. The point is that many problems use `\{ans_rule()\}` early in the problem, and that builds the HTML input field with its HTML `id`. I'm assuming this input element is where `data-` attributes would go that MathQuill could respond to. Later in the PG code, these problems use `ANS` to attach an cmp routine, which can know things about the answer, but the problem is at this point it can't go back and rewrite that HTML input element and give it `data-` attributes. This is my working understanding of how input fields and cmp routines are connected, which I admit I haven't researched in a long time.

I don't think you have looked at the current implementation of the MathQuill answer boxes.  When the ANS rule is later called it is not too late for the options to be added.  The MathQuill answer boxes are added later, and the attributes would need to be put there, and not on the original html input anyway.  The bad idea is to make WeBWorK behave differently for PGML and PG problems and taking uniformity away from the appearance for the end user, as well as making it difficult for instructors to choose problems that provide that uniformity.

I think we are also having a communication issue on what "WW front end" behavior is.  I am not sure what you mean by that, but I think I don't see that as the same thing as you do based on the comments that have been made.

**Comment by mgage** [comment]
On Jan 8, 2020, at 7:49 PM, Alex Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:

When you use PGML's [_]{$ans} then PGML.pl gives you the opportunity to know things about the answer at the same time you will go build the HTML input field. Even using $ans->ans_rule when $ans is a MathObject is, I think, not giving you this. I think that as currently implemented, that usually calls some more basic answer rule constructor without passing the MathObject itself. (If that much is true, it could be changed.) PGML with a MathObject is the one scenario where I can see the two things being tied together already.

I’d assumed that [__]{$ans} was actually translated into $ans->ans_rule but I admit I haven’t checked yet. (it’s late)   Some mathobjects call the default ans_rule but others do something different.
In particular if $ans is a matrix object then you get a whole matrix of answer boxes. So for MathObject matrices and answer boxes are already closely tied together.
For legacy matrices not so much.

Even if there is just one ans_rule you can decorate it according to the type
of MathObject you have or even according to the contents of the MathObject $ans (assuming the contents doesn’t change after you print the answer box).

With javascript and css you can decorate the answer boxes very late in the game — that is how the red and green highlighting is added to the
answer boxes if answers have already been entered.

**Comment by mgage** [comment]
In my experience the most important use of $refreshCachedImages as an author
is to turn it on while I am debugging the problem and then turn it off when I’m done.

As I recall this was implemented by John Jones to make it easier to author and debug problems containing images
without having to constantly go delete the cache on the server, then delete the cache on the browser in order to
see if the changes you have made are actually taking effect in the image. (An error prone procedure that slows
down debugging.)  In this case it’s useful to turn it on for one problem.

You can make a case for turning it on
from the homework set or the editor
but at the time it was easier to store the flag information in the problem rather than add additional
flags to the homework set description of the problem.

Take care,
Mike

On Jan 8, 2020, at 7:49 PM, Alex Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:


At the risk of derailing the thread,

Whether or not an image should be regenerated depends on if it needs to be regenerated due to being a dynamic image or a static image or other considerations

is making my point better than I could. Ideally the image should have an attribute/property that indicates it is dynamic/static. That's the thing that is intrinsic to the problem. (Really, to the image within the problem, even better.) The setting of that property could be automated in some scenarios, explicitly set by the author in others.

If the author is thinking about refreshCachedImages they are thinking two steps down the line in the narrower context of WW HTML output. They should be free from thinking too much about the output mode (unless they keep the problem to themselves and don't share with the OPL or others). The system could deduce whether to refresh based on the appropriate image properties (including file size).

**Comment by drgrice1** [comment]
This has been fixed.
