### ISSUE TITLE
Remove math elements from tab order

### ISSUE THREAD

**Issue by shreyasminocha** [openwebwork/webwork2#1147]
Tabbing through the inputs in problems also tabs over mathjax elements (of the `.MathJax` css class). This can get annoying when you're trying to fill several inputs without using the mouse.

While this behavior can be disabled by each user—by right clicking on any math element, clicking <kbd>Accessibility</kbd>, and unchecking <kbd>Include in tab order</kbd>—it would be better, in my opinion, to disable it by default.

Mathjax has a [`inTabOrder` configuration option](https://docs.mathjax.org/en/latest/options/menu.html#the-configuration-block) which, if set to `false`, would probably fix this.

**Comment by dpvc** [comment]
This will disable the accessibility features for MathJax, and make it much harder for students with assistive needs.  The fact that the math is in the tab order may be the only way for those users to be aware that the math has a menu where accessibility can be enabled.  For example, a blind user may not be able to locate the math in any other way, and so would not be able to access the menu to turn on the needed features.  It is much easier for a sighted person to turn off the MathJax feature than for a blind user to turn it on.  If we are to support the assistive community, we should be making things easier for them, not ourselves.

Finally, the accessibility community is often hesitant to enable features that point out their disability (for privacy and discrimination issues).  Although that probably is not a concern in a WeBWorK setting, you should be aware that the ethos in that community is very much against having to enable accessibility features themselves, in general.

For these reasons, I would object to making the requested change.

**Comment by shreyasminocha** [comment]
@dpvc Fair enough. Is there a way, then, to have something that signals a11y-related settings in the tab order *once*, maybe even before the problems rather than including every math element in the tab order?

![-3 (text input) times {2, -5, 5} (focused) + -2 (text input) times {-3, 4, -3} + 1 (text input) times {0, -7, 9} = {0, 0, 0}](https://user-images.githubusercontent.com/11537232/95475935-44ccde80-0976-11eb-99cc-a66448732533.png)

In this example, every matrix is included in the tab order. Perhaps there could be something before the solution inputs that signals the Mathjax accessibility settings.

**Comment by drgrice1** [comment]
Note that once you set MathJax to exclude one element from the tab order, that effect is saved for the browser.  So that means anytime that all MathJax elements are excluded from the tab order, and stay that way for every page you open that uses MathJax.  So I am not sure that this is something worth doing.

**Comment by dpvc** [comment]
The menu is not just for turning on and off the settings, but also for access to the TeX or MathML that produces the expression, as well as features like the interactive expression explorer.  Since these are expression-specific, they need to be available on each expression.

@drgrice1 is correct that the setting is "sticky", but note that the setting is site-specific, so if a user changes the setting on a WeBWorK page, it will only affect pages that come from that same server.  Also, only the changes made by the explicitly by the user using the menu are sticky, so default settings used by the server will not affect other pages where the defaults may be different.

**Comment by drgrice1** [comment]
Of course MathJax uses cookies to save the setting, so I should have known the settings would be site specific.
