### ISSUE TITLE
UTF-8 not enabled in Achievements score csv, patch attached.

### ISSUE THREAD

**Issue by robert-marik** [openwebwork/webwork2#1158]
UTF-8 is not enabled in Achievements score csv. A short patch is attached.
[webwork_utf8_achievements.patch.zip](https://github.com/openwebwork/webwork2/files/5536912/webwork_utf8_achievements.patch.zip)

**Comment by taniwallach** [comment]
This looks fine. I have never tried out achievements, and apparently no one else actively using the UTF-8 support and a non-English laguage from WW 2.15 has either, so had not run into the issue.

1. Please make a pull request just with the change.
    - I do no think you need `use utf8;` as that is only needed when there are UTF-8 characters in the Perl source file, not for processing UTF-8 data in other places.
2. If possible, post the error message you were getting before the patch in the discussion thread here or that of the PR, so that people who encounter the problem will have a chance to find this patch via a search using Google or GitHub.

**Comment by robert-marik** [comment]
Another issue is that the export of achievements issues error messages if UTF-8 is used in the name or description of the achievement. The attached patch solves both issues.  The pull request is on my todo list, but I am still confused with the github system :(

[AchievementEvaluator.pm_merged_2.patch.txt](https://github.com/openwebwork/webwork2/files/5956450/AchievementEvaluator.pm_merged_2.patch.txt)

**Comment by robert-marik** [comment]
UTF-8 characters in the name or description of the achievement also make troubles. The export works but with error message (the file if fine, though) and the import fails silently. The attached patch solves the problems. It replaces the previous one. Will do a pull request, but I was not able to make the route to submit the pull request to work.

[Achievements-utf8.zip](https://github.com/openwebwork/webwork2/files/5968887/Achievements-utf8.zip)

**Comment by robert-marik** [comment]
The pull request is at https://github.com/openwebwork/webwork2/pull/1206

**Comment by robert-marik** [comment]
Fixed in https://github.com/openwebwork/webwork2/pull/1206
