### ISSUE TITLE
Problem Editor 3 bugs

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1225]
From `develop`, I am experiencing a bug in Problem Editor 3. Video demonstrating the bug at:
http://spot.pcc.edu/~ajordan/ViewTakeActionBug.mp4

The "Take Action" button is not doing anything helpful. I think it reloads the page, but it does not do anything that responds to the tab selection (like View, Revert). In the video, the problem was a temporary verions so the Revert tab was present. I just tested with a different problem that had the Append tab present. This time, View still did not work. Append did append a copy of the problem to the problem set as problem 4. Then when I go to problem 4 and click Edit3, I see the Revert tab right away. But how could this be since I haven't yet had a chance to edit the problem and View it?

**Comment by taniwallach** [comment]
I don't have develop running at present, but forked off develop and with some early merges of other changes, and I don't seem to see this issue/
  - https://github.com/taniwallach/webwork2/tree/jquery-update_and_PR_1190
  - https://github.com/taniwallach/webwork2/compare/jquery-update_and_PR_1190...openwebwork:develop

Maybe see if refreshing the page or bypassing the browser cache helps - maybe the major JS changes are not yet being properly loaded.

**Comment by drgrice1** [comment]
I am also not seeing this either.

**Comment by drgrice1** [comment]
I have been able to reproduce this now.  There is a minor issue with the javacript caused in a change in the way that jQuery handles things.  jQuery has stopped improperly allowing the checked property of a checkbox to be determined using the `attr` method.  I will create a pull request to fix this soon.

Although there are larger problems with the pg editor that are not new.  There are issues with how temporary file creation is dealt with.

**Comment by drgrice1** [comment]
I want to add that most of this issue that you have stated is not javascript related, and is not new to the develop branch.  It may have been highlighted by the javascript issue though.  In any case that is what I was referring to in the previous comment about the issues with how temporary file creation is handled.

**Comment by drgrice1** [comment]
One problem that I see using ww-21.5 (still present in develop) is the following:

Open a problem in a homework set that is from the OPL.  Then click `edit3`.

`View` is the default selected tab.  Now click `Take Action`.  This shows the problem (in a bootstrap modal by default).  It also creates a temporary file in tmpEdit even though no editing has been done, and there is no need for this.

Now close the editor window, and reload the problem in the homework.  The source file for the current user is now set to the temporary file.

Now click `edit3` again.

The `Revert` tab is now there.  Select that and click `Take Action`.  That deletes the temporary file, and then tries to load it, showing nothing in the editor text area.

Once again go back to the problem in the homework and reload it.  The source_file is still set to the temporary file, and since that no longer exists, you get the problem file is empty warning.

**Comment by Alex-Jordan** [comment]
As far as I can tell, the issue I recorded here is fixed by #1231.

Should we make a new Issue for the temporary file creation issue? Perhaps it should compare the source file to the text in the editor before creating a temporary file. Or perhaps javascript should monitor if you make an edit, but it may be hard to know when you made an edit and then undid that edit.

And then it sounds like there is yet another issue as described by your most recent post.

**Comment by drgrice1** [comment]
I think we can leave it under this issue.  Your general title still applies.

**Comment by pstaabp** [comment]
This is not relevant any more as the pg editor has been completely been rewritten.
