### ISSUE TITLE
Session management with 2.16 pre-release branch

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1300]
We are using the 2.16 pre-release branch and I believe we are experiencing a downside to the changes in session management that were put in place. There is a behavior from before the upgrade that I hope can be recovered.

The old behavior is:
1. Get an Email Instructor message from a student. Click the link, and then enter login/password to enter the course.
2. Return to your email and click the link again. This takes you in without any need to enter a login/password.

Similarly if you first enter WW through an LMS and have an active session in some tab, then clicking an Email Instructor link lets you in without any need to enter a login/password.

The new behavior is:
1. Get an Email Instructor message from a student. Click the link, and then enter login/password to enter the course.
2. Return to your email and click the link again. _You are taken to the login screen and must re-enter login/password._

And if you first enter WW through an LMS and have an active session in some tab, _then clicking an Email Instructor does not just let you in; it takes you to a login screen._

Can we recover the old behavior given the changes made to session management?

**Comment by taniwallach** [comment]
My guess is that this may be related to the SameSite Cookie changes (in the
browsers) and the cookie settings. I suspect that the link in the email
address is treated as a cross-site context, so the browser does not include
the existing session cookie with the page request.

Setting SameSite=None and making the Cookie secure may then help.

If you paste the link into the URL bar the handling may be different.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by Alex-Jordan** [comment]
Thanks @taniwallach . Both things worked. That is, pasting the address would let me in. And after I set `$CookieSameSite = "None";` in localOverrides (and cleared the cache) then clicking these links also works.

I'm out of my understanding with "and making the Cookie secure" though. Is that something I should be able to do now? Or are you referring to possible future WeBWorK development?

**Comment by drgrice1** [comment]
@taniwallach: The SameSite cookie policy affects one site requesting information from a third party site.  A direct link in email is not a third party site, and is not affected by this policy, and will behave the same (with respect to the SameSite policy) as literally typing the link into the URL bar.

@Alex-Jordan:  I am using a `$CookieSameSite = Strict` (the default) and `$CookieSecure = 1` on my site, and if I am signed in to the course and click on the link in the email, I am taken directly into the problem for the student.  Furthermore, I have tested all 6 of the different combinations of settings with those two variables, and with all of these if I am signed into the course, the link just works.  I doubt the cookie settings are the issue here.

**Comment by drgrice1** [comment]
I should point out there is one case where the link will not work.  That is the case that `$CookieSameSite = None` and `$CookieSecure = 0`.  The browser rejects these cookies entirely.  With this setting you must sign in with every page you try to open in WeBWorK as well.  Of course that is an invalid setting for any site.

**Comment by taniwallach** [comment]
> I'm out of my understanding with "and making the Cookie secure" though. Is that something I should be able to do now? Or are you referring to possible future WeBWorK development?

You would just uncomment a line in `conf/localOverrides.conf` to get:
```
$CookieSecure = 1;
```

---

> I should point out there is one case where the link will not work. That is the case that `$CookieSameSite = None` and `$CookieSecure = 0`. The browser rejects these cookies entirely. With this setting you must sign in with every page you try to open in WeBWorK as well. Of course that is an invalid setting for any site.

That is certainly meant to be an invalid settings now, but I'm not sure which browsers are already enforcing this by default. It seems that Chrome may be:
  - https://www.chromium.org/updates/same-site
  - https://hacks.mozilla.org/2020/08/changes-to-samesite-cookie-behavior/

**Comment by drgrice1** [comment]
> > @taniwallach: The SameSite cookie policy affects one site requesting information from a third party site. A direct link in email is not a third party site, and is not affected by this policy, and will behave the same (with respect to the SameSite policy) as literally typing the link into the URL bar.
> 
> I think this could depend on the type of mail client being used. I suspect that in a "web-mail" type email interface, a link inside an email can be treated as one from a third-party site, in which case a "SameSite=Strict" setting could cause a problem.

That is still not true.  If you click on a link on a website or in any email (web interface or not), that link will open the site that is linked to in its first-party context.  The site will set its cookies regardless.  The question is if it will send them back to the site from whence you clicked the link, but that has no bearing on the first party site setting its cookies.  Whether the cookies from the site on which you clicked the link are sent or not depends on the SameSite settings on that site and have nothing to do with the SameSite settings on the site the link points to.  Third-party refers to a one site requesting resources from another.  The site that the link takes you to could request resources from the original site using its cookies if sent.  The original site is not making a request for resources from the linked site.  It is just sending the user to the linked site.

To simplify the above explanation, the point is that a site always sets its cookies (unless rejected by the browser due to invalid settings or the user disables cookies for the site).  The SameSite setting only affects whether or not those cookies are sent to a third-party site.

**Comment by drgrice1** [comment]
Okay, nevermind.  I was wrong in the last comment.  If using a web interface for email, the cookies are not set if SameSite is `Strict`.

**Comment by drgrice1** [comment]
Yeah, I think that the default should be set to `Lax`.  That will maintain the default behavior from before.

**Comment by taniwallach** [comment]
https://github.com/openwebwork/webwork2/pull/1307 changed the default to `Lax`.

@Alex-Jordan - I think we can close this issue. Correct?
