### ISSUE TITLE
less than sign math issue, possibly relating to MathJax3

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1315]
In a 2.15 server, this minimal example comes out as expected:

```
BEGIN_TEXT
\(1<x\)
END_TEXT
```

But on my production 2.16 server, the above does not process as desired  in HTML. Basically it comes out in such a way that the web browser is interpreting `<x` as the start of an HTML tag. You see the `\(1` in output.

@dpvc Is this a MathJax3 issue? Or should we edit the math_ev3 routine (or whatever its name is, I forget right now) in WeBWorK to do insert spaces after less than signs?

**Comment by Alex-Jordan** [comment]
Note that I can change it to
```
BEGIN_TEXT
\(1< x\)
END_TEXT
```
and then it comes out as desired.

**Comment by Alex-Jordan** [comment]
This is a MathJax issue, so I will close it and bring it up on a MathJax forum or issue reporter. I'm unsure if it is a bug or if you just should not be using `<` inside MathJax math content. But note that this means some problems which worked for 2.15 will not work for 2.16 unless either MathJax changes, or we proactively do something about it in WeBWorK.

**Comment by dpvc** [comment]
> @dpvc Is this a MathJax3 issue? 

No.  Because the DOM is parsed long before MathJax runs, there is nothing MathJax can do to prevent the browser from treating `<x` as a tag.  See the [documentation](https://docs.mathjax.org/en/latest/input/tex/html.html) for some details.

Because the math is now part of the test of the document, HTML special characters (`<`, `&` and `>`) should converted o HTML entities (`&lt;`, `&amp;`, `&gt;`).  I should have through too this during the v3 update, but didn't.  The reason it wasn't needed when WeBWorK used v2 is that we used the v2 Math `<script>` tags, and the contents of `<script>` tags is CDATA automatically.  But for plain text, as it is now, you need to escape the special characters.

**Comment by Alex-Jordan** [comment]
Reopening this. What needs to happen is we HTML escape math content.

**Comment by Alex-Jordan** [comment]
What are the supported values for displayMode? In `PG.pm` I find:

```
use constant DISPLAY_MODES => {
        # display name   # mode name
        tex           => "TeX",
        plainText     => "HTML",
        images        => "HTML_dpng",
        MathJax       => "HTML_MathJax",
        PTX           => "PTX",
};
```

So when I see things like `HTML_tth` in `PGbasicmacros.pl`, can I clear that out? Also `HTML_img`, `HTML_jsMath`, `HTML_asciimath`, `HTML_LaTeXMathML`? I'm just adding the HTML escaping for `HTML_MathJax` output and I see all these other things.

**Comment by drgrice1** [comment]
The HTML_tth, HTML_jsMath, HTML_asciimath, and HTML_LaTeXMathML modes are deprecated as I understand it.  There is also Latex2HTML that is used in PGbasicmacros.pl, and I believe is deprecated.  @mgage mentioned cleaning this up and removing those from the code.

**Comment by taniwallach** [comment]
Fixed by https://github.com/openwebwork/webwork2/pull/1322
