### ISSUE TITLE
answer log no longer recording submit versus preview

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1340]
Before upgrading to 2.16, my production server logged answers in the answer log like:

```
[Tue Mar 09 22:12:35 2021] |alex.jordan|Module_1_Quiz,v1|2|1	1615356755	[submit] 2sqrt(470)
```

Note the `[submit]` field. (Actually it's not a field since it is followed by a space, not a tab.) That could also be `[preview]` if the student clicked a preview. This was useful for looking up when a student had only previewed their answers in a set, thinking they had submitted. It was useful beyond the quiz context. With regular homework sets, a student who is still unfamiliar with WeBWorK might hit Enter for their answers as they go, merely previewing them.

It looks like this was removed in 6069af9717f95da0f1ed93000c17be08b66fa151. My guess is it was assumed this was only there for quizzes, which now have better handling to store answers in the more delicate quiz setting. Does something else replace that functionality for regular homework sets?

**Comment by drgrice1** [comment]
This was intentional.  Those past answers were messing up the past answer table when viewing them on the "Past Answers" page.  There was also an issue with the applet states being stored in that column.   Furthermore this was inconsistent with homework sets that do not save anything to the past answer table when preview is clicked.  You seem to be claiming this was added with homework sets, but as I just said that was never true.

Note that you still will get the information when "submit" is clicked, but that is now the only time.  It will not be prefixed with "[submit]" though.

I do not consider this a bug.  The bug was really that it was done that way before.

**Comment by Alex-Jordan** [comment]
I must be mistaken that this was there for regular homework sets. I know I used this to deal with a few cases of students having "lost" their answers. But I guess it must have been only with quizzes and I never realized it was not there for homework.
