### ISSUE TITLE
MathQuill and DraggableProof

### ISSUE THREAD

**Issue by pschan-gh** [openwebwork/webwork2#1452]
This seems to be an issue for both WeBWorK 2.15 and 2.16.

In a problem like:
Library/Hope/Multi1/03-01-Vector-spaces/Proof_04.pg
with multiple DraggableProof sub-problems, if MathQuill is enabled only those sub-problems with the most recently submitted answers have the answers stored. Unless one gets all parts correct in one submission, older answers are forgotten.

In WeBWorK 2.16, the problem can be fixed if one sets $ans->{mathQuillOpts} = 'disabled'; in draggableproof.pl, but I suppose it is more proper to  fix the problem at its root.

**Comment by drgrice1** [comment]
The draggable proof macro is broken, and really needs to be completely rewritten.  One looming problem is that it relies on an obsolete javascript library (jquery.nestable) that hasn't been maintained for a long time.  The last time that there were any changes to its code was in 2017, and that was a minor change that certainly didn't do much.  Really, it hasn't been maintained since 2014.  Furthermore, the library was never fully developed to begin with,  and even claims this on its project page.  Here is what is stated there:

> I cannot provide any support or guidance beyond this README. If this code helps you that's great but I have no plans to develop Nestable beyond this demo (it's not a final product and has limited functionality). I cannot reply to any requests for help.

Furthermore, that library depends on jquery-ui which is also unmaintained and we plan to drop jquery-ui from the javascript dependencies soon.

**Comment by pschan-gh** [comment]
I see, that's good to know. Thank you.
