### ISSUE TITLE
WW 2.16 Missing the msgid "Import" in the translation files for the label on the set editor / user editor import tab

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork2#1477]
The `msgid "Import"` was moved in the PO translation files into a comment at the bottom of the file. It used to provide the translation for the "label" on the Import tab of the set editor.

This occurred in WW 2.16, but the string was available for translation in WW 2.15.

It seems that this probably occurred as part of the changes in https://github.com/openwebwork/webwork2/pull/1371 . That PR certainly added a section with 3 `contant` labels under the comment line
```
# capture names for maketext
```
and it seems that they are needed as the text displayed seems to be set by https://github.com/openwebwork/webwork2/blob/b9b4e45b771b5e250eb275f3aa2c88337203d879/lib/WeBWorK/ContentGenerator/Instructor/ProblemSetList.pm#L595 which uses `$r->maketext(ucfirst(WeBWorK::split_cap($actionID)))`  but that an additional one
```
use constant mk_publish => x('Import');
```
will be needed.

@drgrice1 - Do you agree that this is the cause of the problem and the proper approach to fixing it?

**Comment by taniwallach** [comment]
The same issue effects also the user editor page.

**Comment by drgrice1** [comment]
The reason that the string "Import" was in the po/pot files for WeBWorK-2.15 is due to the fact that maketext was called on the original (now removed) ProblemSetList.pm file on line 1238.  The 3 lines under `# capture names for maketext` were not added by the pull request, but were moved from another place in the ProblemSetList2.pm file (where they shoudn't have been).

I agree that adding `use constant mk_import => x('Import');` will fix the problem, and that is probably good enough for now.

However, I do not agree that this is the correct way to fix the problem.  In fact, this instance is a case in point that this is not the correct way to do this.  Anytime that you are calling maketext on something that is not a literal string, you are probably doing it incorrectly.  The problem is that this technique of calling maketext does not ensure that the strings coming from something like `ucfirst(WeBWorK::split_cap($actionID))` are all properly captured as there is not a direct correlation to the possible strings that could be translated.  I suspect there are other strings that are not translated in this case also.  For example, I don't see the strings "Cancel Edit", "Save Edit", "Save Export", or "Cancel Export" in the po/pot files either.  Those were also not there in WeBWorK-2.15.

When I moved the `# capture names for maketext` where they now are, I did so because they are right by the form names that they are translations for.  At the time I also noticed the lack of the other strings and intended to go back and investigate, but forgot about it later.

**Comment by taniwallach** [comment]
@drgrice1 I agree that calling maketext on a non-literal string is not an optimal or advisable approach. I did not mean to assign any blame for the current code, just to consult with you on how we should address the problem. I think we should consider if there is a better approach to use which we could reasonably implement now, or whether to just apply the "good enough for now" fix (also for the 4 other mentioned strings).

Whoever wrote the code using `maketext(ucfirst(WeBWorK::split_cap($actionID)))` for what was once `ProblemSetList2.pm` and is now `ProblemSetList.pm` apparently wanted to create the "tabs" in a generic manner based on the value of `$actionID`, so used the approach they did. The code seem to data back about 10 years: https://github.com/openwebwork/webwork2/pull/5/commits/e3e87c56e4c253d4fa6044f243018be7e54be07f and that old commit already has the `maketext` call in it.

One approach I can think of to avoid calling `maketext` on some code-generated value based on `$actionID` would be to call a new function which would run through the possible values of `$actionID` (`if-then` or `switch` style) and make the `maketext` call with a suitable literal string (and probably to include a fall-back case at the end). Such an approach would have a run-time penalty on each invocation, so I'm not convinced that is really a better approach than just creating these constants to force the relevant strings into the dictionaries as done at present.

Another approach would be to create a hash whose keys are the possible values of `$actionID` and whose values were the results of the suitable `maketext` calls. It seems that the hash needs to be recreated each time the relevant code is running, so the `maketext` call would "know" the current language to use for the course in use. That is slightly more direct than the current hack, but still not very "nice".

Do you have a better idea?

The approach using `maketext(ucfirst(WeBWorK::split_cap($actionID))))))` is used in the current versions of:
  - `lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm`
  - `lib/WeBWorK/ContentGenerator/Instructor/UserList.pm`
  - `lib/WeBWorK/ContentGenerator/Instructor/ProblemSetList.pm`

BTW I never really paid attention to the "Cancel Edit", "Save Edit", "Save Export", or "Cancel Export" tabs, as either the action would be applied or I would just navigate away. As a result, I did not pay any attention to these strings not being translated or available to be translated.

The "Import" stands out in WW 2.16 in Hebrew as a tab which is not translated, while it was translated in the past. In WW 2.15 "Filter" was not translated, which was a mild annoyance.

---

There is a somewhat similar problems with a few "special codes" which are "translated" also for English (and which Transifex does not handle well). See https://github.com/openwebwork/webwork2/commit/7f7bb3889b33cba10b9515d0af6198cedd984071#diff-f45fec1d99616872e2f6dbaa76e9743dd8dc8e8f38ef4492dd3ba1dce0bf46a1

**Comment by drgrice1** [comment]
The `if-then` or `switch` style approach is certainly not very nice or desirable.  The problem with using a hash of actionIds and text is the usual problem of then also needing an array to maintain order.

Another approach would be to add a method (something like `${actionId}_title`) for each '$actionId` that would be called to obtain the title.  This would work like the current `${actionId}_handler` and `${actionId}_form` methods.  So for the `edit` action there are currently the `edit_handler` and `edit_form` methods.  Now add a `edit_title` method that simply returns `$r->maketext("Edit")`.   This approach would be efficient.

**Comment by taniwallach** [comment]
OK - in progress.

**Comment by drgrice1** [comment]
Probably the simplest way to do this is the way it is already done in
`lib/WeBWorK/ContentGenerator/Instructor/AchievementEditor.pm` and
`lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm`.   That approach is perhaps not calling maketext on a literal string, but there still is a rather direct mapping to the things that can appear in the maketext calls.

In the case of the other three files (`ProblemSetList.pm`, `AchievementList.pm`, and `UserList.pm`) a single `FORM_TITLES` constant could be used containing all of the possible translations.

**Comment by drgrice1** [comment]
Here is a patch that implements my first suggestion in ProblemSetList.pm.

[method-approach.zip](https://github.com/openwebwork/webwork2/files/6992420/method-approach.zip)
