### ISSUE TITLE
Move pg-only related configuration from WW2 to PG

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#1568]
There are many configuration items in webwork2 in `defaults.conf`, `site.conf`, `localOverrides.conf` that need to be moved into PG. Including
- [ ] pg variables in defaults.config. Line 1334.
- [ ] hardcopy themes

**Comment by drgrice1** [comment]
This issue is not entirely valid.  The client using the PG library needs to be able to configure PG.  PG does have its configuration variables, but the client sets them.  For webwork2 those are in `defaults.config`.

The hardcopy themes are another matter.  Those are really webwork2 specific.  PG can output TeX, but it is up to the client to decide how to put it all together for compilation.  Just like for html PG does not render a full html page, but rather an html snippet to insert into a page.

So I am closing this issue.
