### ISSUE TITLE
[Feature Request]: Percentage complete in main homework set listing.

### ISSUE THREAD

**Issue by AVolkoff6** [openwebwork/webwork2#1582]
When looking through all available homework sets, there is no way to see the amount of problems completed in each one without opening every set separately. Being able to view the completion percentage in the main view would help prevent accidentally missing problems.

**Comment by somiaj** [comment]
@AVolkoff6 this information located in the 'Grades' page. There you can see all homework sets, the overall grade, and the grade on each problem, so you can see exactly which problems have not earned full credit. 

Though there an issue with displaying the current grade, since it could be that all attempts have been used or the assignment was done in the reduced scoring period, so the problem is complete, just full credit was not earned. In this case one would still end up having to click on each problem individually to see why the grade isn't 100%. This is partly being discussed here https://github.com/openwebwork/pg/issues/648#issuecomment-1029327132.
