### ISSUE TITLE
Increasing character limit for course name

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1713]
Is there any objection to raising the character count on a course name? It's currently 40. The input field in the admin course won't let me go past 40, and I assume the database field is configured that way too.

With Runestone hosting, with multiple schools, we are using a naming convention that includes the school name, instructor name, course number, and term/semester.  Every once in a while it is a bit longer than 40. Actually I've only ever noticed it being a few characters too long. If we could raise this to 50 it would be more than enough.

If this is an OK thing to do, I would need some help. I have never touched the database and I'm not sure where to begin.

**Comment by drgrice1** [comment]
With the current webwork2 database structure, I do not believe that there is a single character that can be added to the allowed length.  This is because we use the course name for the start of all of the database table names for it.  There is a limit on the length of a mysql table name.  That limit is 64 characters.  So if a course id is 40 characters long, then the lengths of the table names will be 40 characters plus the suffix.  The global user achievement table (the longest name) would then be exactly 64 characters long.  It is courseId_global_user_achievement.

The next longest is the set locations user table which adds 19 characters.  So that would allow 45 characters for the course id if the global user achievement table name were shorter.

Considering the massive restructuring of the database and the upgrade code that would be needed for past courses that would be required for this, I think the answer is probably no to this idea, and wait for webwork3.

**Comment by Alex-Jordan** [comment]
OK, thanks for your insight on this. I will have to be content with deviating form our naming convention when needed.

**Comment by drgrice1** [comment]
Yeah, sorry.  More and more we are seeing the limitations of the webwork2 database structure.
