### ISSUE TITLE
untracked webwork2/htdocs/applets/ folder

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#1728]
`webwork2/htdocs/applets/` is showing up as an untracked folder by git. All it has is symbolic links to the OPL. Is everything in order here? Should this folder be tracked? Is git unwilling to track a folder that only has symlinks or something? Should this folder be in `.gitignore`? I have those kinds of questions.

**Comment by drgrice1** [comment]
That folder definitely should not be tracked and should not be ignored.  It should be deleted if you still have it from old versions of webwork.

**Comment by Alex-Jordan** [comment]
OK, thanks. If this folder was tracked and git deleted, does it make sense to you that it's still there on my server? I would have thought if it was supposed to be deleted, git would have done that.

**Comment by drgrice1** [comment]
The symlinks that you mentioned are left over from webwork 2.15 and before (the generation of those links was removed in 2.16).  Since those links were generated and at the time ignored by git, but are no longer ignored, git will neither delete them nor the directory containing them.  It is now safe to completely delete that directory though.

**Comment by Alex-Jordan** [comment]
OK, that makes sense. Next question: does it make sense to add this to the upgrade instructions?
