### ISSUE TITLE
OPL-update

### ISSUE THREAD

**Issue by apizer** [openwebwork/webwork2#1769]
I am in the process of updating the https://webwork.maa.org/wiki/Installation_Manual_for_2.17_on_Ubuntu manual and am at the point of installing the OPL.  When I run OPL-update I get an error in attempting to upload the OPL-statistics. This hasn't worked for years and is something I hope is reinstituted soon but that is besides the point.  Usually OPL-update is run before a semester or when setting up WeBWorK and uploading OPL-statistics is run after the semester is over so I am not sure why it is in OPL-update and is set to run by default.  It would be better to leave it out or at least ask weather to run it or not.  It is controlled by $ENV{SKIP_UPLOAD_OPL_statistics.  Running
wwadmin@wwserver:/opt/webwork/webwork2$ grep -R SKIP_UPLOAD_OPL_statistics *
I see only two places in the webwork2 code that it appears:
bin/OPL-update:  if ( $ENV{SKIP_UPLOAD_OPL_statistics} ) {
docker-config/docker-entrypoint.sh:        export SKIP_UPLOAD_OPL_statistics=1

At this point what is the best way to handle this?  Any help or suggestions appreciated.

**Comment by drdrew42** [comment]
The OPL statistics upload has been reinstated (although, due to some campus network issues, the receiving server is temporarily offline right now). You are correct that the upload is pointless on any fresh install. However, the concern was that separating out the upload OPL statistics script would make it more easily overlooked or ignored -- particularly because the upload script has not worked for several years.

On manual install (as opposed to docker build), OPL-update without upload can be run in two lines:
```bash
wwadmin@wwserver$ export SKIP_UPLOAD_OPL_statistics=1
wwadmin@wwserver$ OPL-update
```
or it can be run in one line:
```bash
wwadmin@wwserver$ SKIP_UPLOAD_OPL_statistics=1 OPL-update
```

Systems that are upgrading (rather than a fresh install) _should_ upload their statistics -- this provides valuable insight into the use of OPL content, and the whole community will benefit. All shared data is aggregated by problem path, and as such, there is no individual information (PII) in the data and it is completely safe to share.

**Comment by apizer** [comment]
Thanks.  Glad OPL statistics are being collected again.

**Comment by apizer** [comment]
Hi,

I think we may get some pushback from how OPL-Update works and I think we should think hard about this.  I am very happy that we are collecting OPL-statistics again but I think we have to be very sensitive about how student data is sent back to us. At present, a professor runs OPL-update to update the OPL and (surprise) they see that they are sending student data to some unknown ip address with no explanation, opt in, warning or clear way to break out of the process. Has the data already been sent before they hit Control C? Panic! I think this is a very bad process. Just ask your local IRB officer what they think of this. They might tell you to shut down WeBWorK immediately.  I understand that we want to encourage people to send data and make it as easy as possible, but I think there has to be a better way.  For one thing there should be a question about whether or not the professor wants to send in the data and they should be directed to a wiki page (in addition to https://webwork.maa.org/wiki/OPL_Problem_Statistics) that explains in detail what is involved.  The wiki page maybe can cover some of the points I made when I sent out the original personal requests for data back in 2015 (see below).  Probably most of the current data comes from UR, MAA, and responses to that request.  Important points as I see it (copied from original letter which should be brought up to date) are:

1. There is no student identifying data being requested
2.  Then maybe you should contact your IRB office and tell them that you are planning on contributing data and show them the OPL_local_statistics table (or the sample above) so they can see that no student identifying data is involved.  After receiving their blessing, ...
3.  Your local data will get sent to a server that Geoff Goehle (who has written most of the code for this project) is maintaining.  The resulting OPL_global_statistics table will be distributed as part of the OPL.

Sending student data off campus was a sensitive topic in 2015 and I'll bet it is even more sensitive today.

Just my two cents.

Arnie

Here is a copy of one of my original solicitation letters.
                                                                                                                                                              Thu, Oct 22, 2015, 4:32 PM
Hi Ted,

This is a request for OPL problem data from your institution.  In a future version of WeBWorK (probably 2.12) the Library Browser will optionally display local and global data about problems, specifically the number of individuals who have attempted the problem, the average number of attempts on the problem and the average status earned on the problem.  Local data represents usage at your institution and global data represents the sum of all local data contributions. The display will look like

![image](https://user-images.githubusercontent.com/1406230/182262658-41e28ddb-b090-4b8e-9ad3-597101280b46.png)

The data that we are requesting you generate and contribute goes in a MySQL table OPL_local_statistics where entries look like:

+--------------------------------------------------+--------------------+------------------+----------------+
| source_file                                      | students_attempted | average_attempts | average_status |
+--------------------------------------------------+--------------------+------------------+----------------+
| Library/LoyolaChicago/Precalc/Chap4Sec2/Q02.pg   |                  2 |                3 |             .5 |
+--------------------------------------------------+--------------------+------------------+----------------+

so, as you can see, there is no student identifying data being requested.

In order to get this project (which is a small and independent part of the WeBWorK "Big Data" project) off the ground, we need global data.  Hence this personal request for data from your institution.

If you are interested in contributing (and we hope you are), the process is very easy. First download two scripts with the following commands:

wget --no-check-cert https://raw.githubusercontent.com/goehle/webwork2/dbscript/bin/update-OPL-statistics
wget --no-check-cert https://raw.githubusercontent.com/goehle/webwork2/dbscript/bin/upload-OPL-statistics

You can put them in /opt/webwork/webwork2/bin/ if you want.  They should run on any recent version of WeBWorK but have only been tested on 2.7, 2.9 and 2.10.  Run
perl update-OPL-statistics
which generates the OPL_local_statistics table.  In the future you should probably run update-OPL-statistics at the end of every semester. It harvests data from all closed (due date has passed) homework sets and is written so that old data (e.g. from courses deleted since the last time the script was run or from courses that are reused by deleting old students and adding new ones or just old courses that remain on the server) is saved and new data is properly handled.   It does not retrieve data from archived courses.

Then maybe you should contact your IRB office and tell them that you are planning on contributing data and show them the OPL_local_statistics table (or the sample above) so they can see that no student identifying data is involved.  After receiving their blessing, to upload the data, run the command
perl upload-OPL-statistics

That's it.  Your local data will get sent to a server that Geoff Goehle (who has written most of the code for this project) is maintaining.  The resulting OPL_global_statistics table will be distributed as part of the OPL.

If you are interested in seeing how this actually works in the Library Browser, do the following on your development system.

git checkout origin/develop
git pull http://github.com/goehle/webwork2.git dbscript
Update localOverrides.conf from localOverrides.conf.dist and run
apachectl restart

Then run
update-OPL-statistics
if you haven't run that yet.  Also it's a good idea to first update the OPL if you haven't done that in awhile. Either turn off the global data option (in localOverrides.conf) or create a fake OPL_global_statistics table, e.g a copy of OPL_local_statistics (maybe very soon with your help we will have a real OPL_global_statistics table available).  Note that if no data is available for a problem you are looking at in the Library Browser, you will not see labels with 0's displayed.

Thanks for any help you can give us with this and feel free to write with any questions, comments or suggestions.

Sincerely,

Arnie

--
Prof. Arnold K. Pizer
Dept. of Mathematics
University of Rochester
Rochester, NY 14627
(585) 766-8812

**Comment by drdrew42** [comment]
I respectfully disagree with your overall assessment of the situation. The fact of the matter is that we are not collecting _any_ student data at all. The data in question is strictly usage statistics for problems in the OPL, yet several times you refer to this as 'student data' -- which it simply is not. Even in the 'worst' possible case, we'll only know that there exists **a** user from University X who tried a problem and got some score. Even in such an unlikely scenario, there is no possible way to identify the user.

Yes, we probably should add an escape clause to the upload script, but recommending that site admins initiate IRB review is going to scare people off more often than not. Even *if* the site admin has knowledge about how to initiate IRB review, these things can be extremely cumbersome -- and it's unnecessary in the first place. And if they are *not* familiar with the process, it won't matter that IRB doesn't apply, because things are unlikely to even get that far.

Simply put, as the ones collecting the data, we know for a fact that this data collection effort in no way runs afoul of any student data protections, because it is not open to interpretation that **aggregate data is not personal data**. Suggesting otherwise only casts doubt and raises alarms unnecessarily. 

For transparency sake, I will add an escape clause to the upload script and a paragraph describing the data that will be sent. I suggest something along the lines of:

WeBWorK and the Open Problem Library (OPL) are provided freely under an open-source license. We ask that you share your OPL usage statistics for the benefit of all who use WeBWorK. The following information will be shared with the WeBWorK community if you agree:
- a list of OPL problems that have been used on your server, with the following statistics for each:
  - the total number of users who attempted the problem
  - the average number of attempts made per user on the problem
  - the average completion percentage for each user who attempted the problem

Share OPL usage statistics with the WeBWorK community [Y/N]: _
<continue with upload script or exit>

**Comment by apizer** [comment]
I think your proposed changes would be a major improvement.
