### ISSUE TITLE
Strange behavior from one of the seeds of a problem

### ISSUE THREAD

**Issue by ReginaSouza321** [openwebwork/webwork2#1836]
Issues with problem

Library/MT/11-3/c9s3Q43.pg   

seed 655 of this problem is "crashing" 

My student was able to complete the problem but it crashed several times in between

(I'm afraid this is not in the "MT" library and I'm afraid you are not "maintaining" these problems.)

Hopefully you can tell me what to do.

Actually, I'm not sure I'm reporting to the correct site. It's webwork2, but not openwebwork?

https://lennes.math.umt.edu/webwork2/121-CollegeAlgebra_2022F/3.3b_More_graphs_and_applications/5/?effectiveUser=souza

**Comment by drgrice1** [comment]
That problem does not seem to actually be a problem in the OPL.  Is that a local file for your server?

**Comment by ReginaSouza321** [comment]
Might be. Do you have a suggestion on how to get it looked at? (I suspect
it was a problem in the OPL without a solution) One of our colleagues (Dick
Lane, retired) wrote solutions for many problems and I suspect he may not
have submitted then to the OPL. Or, he did, and I'm still using an older
version. Do you have a suggestion on how to go about it?

**Comment by drgrice1** [comment]
Most likely you should ask about this on the WeBWorK problem authoring forum (https://webwork.maa.org/moodle/mod/forum/view.php?f=3).  You will probably need to attach the source of the problem.  It may just be me that ends up helping you there also, but that is the correct forum for this.  There are many others that may see this there that may be able to help you as well.  Not as many follow the github issues.

I am closing this issue as it does not belong here in any case.  If you find that it is due to a bug in PG, then you should open an issue at https://github.com/openwebwork/pg/issues.

**Comment by ReginaSouza321** [comment]
Thanks!

**Comment by pstaabp** [comment]
As mentioned above, this seems to be a bug in a user problem, not a PG bug.
