### ISSUE TITLE
Change name of Hmwk Sets Editor and possibly Classlist Editor

### ISSUE THREAD

**Issue by dlglin** [openwebwork/webwork2#1992]
"Hmwk" needs to be replaced with a full word.  There was discussion about the fact that not all sets are homework, so we should find a different name.  Suggestions include "Assignments" or just "Sets".

Also consensus seemed to be that this should be changed from "Editor" to "Manage".

How about:

- "Classlist Editor" -> "Manage Users"
- "Hmwk Sets Editor" -> "Manage Assignments"

The biggest implication of this would be to existing documentation.  Both internal documentation and custom site-specific documentation refer to the old names, which may make people confused and/or unhappy.

**Comment by pstaabp** [comment]
I would argue to make the new name nouns to roughly fit it with the rest of the name of the tools.  Perhaps:

* "Classlist Editor" -> User Manager
* "Hmwk Sets Editor " Assignment Manager

**Comment by drgrice1** [comment]
It seems that the `Achievement Editor` should also be renamed.  Perhaps to `Achievement Manager`.  The name `Achievement Editor` is confusing when there is also an page that is for editing achievement evaluators that seems more like an `Achievement Editor` than this page.

**Comment by Alex-Jordan** [comment]
For a little while now in develop, in the TOC we've had:
```
User Manager
Set Assigner
Set Manager
```

<img width="252" alt="Screenshot 2023-11-24 at 11 42 49 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/663b4b3d-2005-4e08-840c-d25b0bd7c325">

Each time I go into a course on develop (to test or develop something) I see these and I'm not liking them. At first I thought it was just reflex because they are new and different. But now I'm starting to feel that I dislike these for more than just the bias of familiarity. Does anyone feel similarly? With the repeated use of `Set` and `Manager`, it feels cluttered. Or like it's missing a `User Assigner` to round it out. `Set Assigner` bugs me now, because you can "assign the sets to users" but you could also think of it as "assigning the users to the sets".

It's hard to think of better names. But I'm going to toss out these and see if anything sticks in the opinions of others reading this. In addition to renaming those three, I renamed `Acheivement Editor` as @drgrice1 suggested (except with plural). And also `Homework Sets` at the top of the TOC.

<img width="252" alt="Screenshot 2023-11-24 at 11 48 34 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/5ccf480e-7c69-4c1a-b664-36b97479f324">

**Comment by somiaj** [comment]
I to have had a bit of trouble navigating with the new menu, but still getting use to it. I do like the idea of replacing `Set Assigner` with `Assigner Tool`, this makes it more similar to `Instructor Tools` (which it is just a special case of). That might help make things look a little less similar. I don't know about your other suggestions though, I think they are less descriptive. I think `User Manager` is a better description than `Course Roster`, also I like the repeated use of `Manager` to help distinguish what the page is.

**Comment by Alex-Jordan** [comment]
A few more alternatives I'm trying out:

<img width="252" alt="Screenshot 2023-11-25 at 10 25 55 AM" src="https://github.com/openwebwork/webwork2/assets/4732672/a85cb2f0-15f8-4a9e-9ff2-fc3237c731c8">

This combo eliminates "User". "User" is comfortable for software designers and someone who views drug addiction as a life choice. But if I'm a typical instructor, I don't think of my students as "users".

**Comment by somiaj** [comment]
I like your last suggestion best of them so far. I'm okay with replacing "User", it was the "Manger" part I liked over "Roster".

**Comment by drgrice1** [comment]
I think your last suggestion sounds reasonable.  I also don't like the "Course Roster" suggestion.  That seems to specific when there are more users than just students that are managed on that page, and a roster typically refers to just students enrolled in the course.

**Comment by Alex-Jordan** [comment]
I've lumped a lot of things here, so I should recap:

```
'Homework Sets' => 'Assignments',
'User Settings' => 'Account Settings',
'User Manager'  => ('Course Roster', 'Accounts Manager'),
'Set Assigner'  => 'Assigner Tool',
'Set Manager'   => 'Sets Manager',
'Achievement Editor' => ('Achievement Manager', 'Achievements Manager'),
```

Do all of these sound like improvements? I don't want to impose my taste; whatever subset of these (or new suggestions) people are god with, I'll open a PR. It sounds like `'User Manager'  => 'Accounts Manager'` and `'Set Assigner'  => 'Assigner Tool',` are good.

**Comment by drgrice1** [comment]
I think
```
'Homework Sets' => 'Assignments',
'User Settings' => 'Account Settings',
'User Manager'  => 'Accounts Manager',
'Set Assigner'  => 'Assigner Tool',
'Set Manager'   => 'Sets Manager',
'Achievement Editor' => 'Achievements Manager'
```
sounds good to me.  I think going with consistent plurals is a good idea.

**Comment by somiaj** [comment]
I would be okay with:

```
'Homework Sets'      => 'Assignments',
'User Settings'      => 'Account Settings',
'User Manager'       => 'Accounts Manager'
'Set Assigner'       => 'Assigner Tool',
'Set Manager'        => 'Sets Manager',
'Achievement Editor' => 'Achievements Manager'
```

**Comment by Alex-Jordan** [comment]
Consistent plurals...except not with "File Manager"? I can't bring myself to like "Files Manager". But I'll do it if we like the consistency.

**Comment by drgrice1** [comment]
Yeah, I don't like `Files Manager` either.  I didn't think of that one in this.

**Comment by Alex-Jordan** [comment]
I'm ok with changing the order that way.

I'll mention that on another branch I am revising Instructor Tools to be
better in several ways.

**Comment by Alex-Jordan** [comment]
I like verbs for buttons (basically stay on the same page but change something about the page or submit a form), but nouns for links (go to a new page).

**Comment by pstaabp** [comment]
Changed in #2265
