### ISSUE TITLE
Error with MathQuill turned off

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#2140]
On develop, if you turn math quill off and submit a problem, the following error pops up:
```
DBD::MariaDB::st execute failed: Data too long for column 'frozen_hash' at row 1 at /opt/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 881.
```

**Comment by pstaabp** [comment]
I'm seeing this with math quill turned on as well.  Since this is related to Achievements, turning that off, results in no error.

**Comment by drgrice1** [comment]
You need to update your database columns using the `upgrade-database-to-utf8mb4.pl` script.  That will change the types of the columns to what is in the schema.  The problem here is that `frozen_hash` columns of the global user achievement and user achievement tables in your database are still `VARCHAR(1024)`.  Those need to be changed to type `MEDIUMBLOB`.  You can type `desc courseID_achievement_user` in mysql to see what the type of this column is in your database, and verify that this is indeed the case.
