### ISSUE TITLE
Loading localOverrides.conf in a course.conf comes too late for the LTI tab in Course Config

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2181]
In 2.18, suppose `localOverrides.conf` does _not_ load `authen_LTI.conf`.  But a course's `course.conf` file loads `authen_LTI.conf` instead. And inside `authen_LTI.conf`, there is some uncommenting of `@LTIConfigVariables`. This should reveal the LTI tab in the Course Config page, but it does not.

**Comment by Alex-Jordan** [comment]
I can assign `@LTIConfigVariables` in `localOverrides.conf` without loading `authen_LTI.conf`, and that is enough to reveal the LTI tab. But now it is revealed for all courses which is not desired.

I'm trying to let those courses which use LTI load `authen_LTI.conf`, and leave it out of those courses which do not. (Which I admit may be unnecessary.) So I load `authen_LTI.conf` in some course's `course.conf` file, but that leads to this issue of the LTI tab being absent.

**Comment by drgrice1** [comment]
Have you tried also including the LTIConfigValues.config in the course's course.conf file after including the authen_LTI.conf file? I haven't tested this, but it might work.

**Comment by Alex-Jordan** [comment]
That does work. I guess I don't understand why though. That is already included by `defaults.config`. So why does this help?

**Comment by drgrice1** [comment]
The first time that `LTIConfigValues.config` is included by `defaults.config`, The `@LTIConfigVariables` array is empty (actually it is undefined) since `authen_LTI.conf` has not been included.  So the "LTI" section of the config is not added by the code at the end of `LTIConfigValues.config`.  When `authen_LTI.conf` is included in `course.conf` it defines and populates the `@LTIConfigVariables` array.  So when `LTIConfigValues.conf` is included after that in `course.conf`, the "LTI" section is added.

Fortunately this is all done in the safe compartment without `strict`, and we don't catch warnings when the config files are loaded by the course environment.  Otherwise there would be problems!
