### ISSUE TITLE
https://webwork.maa.org/wiki/Moodle_Assignment and 2.18

### ISSUE THREAD

**Issue by maligokbas** [openwebwork/webwork2#2199]
I am using moodle. In version 2.18 I cannot perform the instructions described at https://webwork.maa.org/wiki/Moodle_Assignment because it uses Mojolicious instead of apache. What can I do to use Moodle Assignment in version 2.18? I'm using docker image on kubernetes.

**Comment by drgrice1** [comment]
This is a question that is more appropriate for the forums so that others can benefit from the conversation, and since this is not actually an issue with the webwork2 code.  The documentation you linked is now out of date, but this can still be done with 2.18.  I can't provide detailed instructions, since I don't have the environment needed to figure out how to do so.  However, I can tell you how to enable the WebworkSOAP handlers.  To do so uncomment `soap_authen_key: 123456789123456789` in `/opt/webwork/webwork2/conf/webwork2.mojolicious.yml`, and change the value to something more secure.

I also highly recommend that you stop using this technique entirely.  This is an obsolete technique for Moodle. LTI authentication replaces this.

**Comment by maligokbas** [comment]
> This is a question that is more appropriate for the forums so that others can benefit from the conversation, and since this is not actually an issue with the webwork2 code. The documentation you linked is now out of date, but this can still be done with 2.18. I can't provide detailed instructions, since I don't have the environment needed to figure out how to do so. However, I can tell you how to enable the WebworkSOAP handlers. To do so uncomment `soap_authen_key: 123456789123456789` in `/opt/webwork/webwork2/conf/webwork2.mojolicious.yml`, and change the value to something more secure.
> 
> I also highly recommend that you stop using this technique entirely. This is an obsolete technique for Moodle. LTI authentication replaces this.

Thank you for your answer. On the Moodle side, it wants me to define a WSDL file in the URL for WeBWorK server WSDL file section (Default: https://test.edu/webwork2_wsdl) in the WeBWorK Assignment settings. I couldn't find a field for it in webwork2.mojolicious.yml. How can I define a WSDL file?

**Comment by drgrice1** [comment]
The url should be the same (`https://your-server.edu/webwork2_wsdl`).  There won't be anything in the `webwork2.mojolicious.yml` file about that.

**Comment by maligokbas** [comment]
Should Active Directory settings be the same as we did before? I made the settings in 2.18 with the settings in the previous version, but I could not log in with the active directory user from within the webwork.

**Comment by drgrice1** [comment]
I don't really know what "Active Directory settings" are or what they should be.

**Comment by drgrice1** [comment]
I am sorry that I am not able to be of more help for you.  I don't know that much about "Moodle Assignment". As I said, it is an obsolete approach to integration with the Moodle LMS.

**Comment by maligokbas** [comment]
Thanks for your help.
