### ISSUE TITLE
Achievement points not awarded during reduced credit period

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2285]
It seems that if you are in the reduced credit window and correctly answer a question, you get no points towards leveling up. I suspect that somewhere, a test is done based on the score being 1, but during reduced credit the score is 0.75 or something less than 1.

Not sure if this should be changed. Users could either get the full amount of achievement points for correctly answering a question during the reduced credit window, or could get that amount scaled by the reduced credit factor. I would support just awarding all the achievement points.

**Comment by drgrice1** [comment]
We need to discuss what we want to do with this.  I have implemented it to make achievements work on the unreduced score.  We just need to decide if this is what is desired.  I have implemented it to give all achievement points and completely ignore the reduced score using the full unreduced score instead.  This can be tweaked to give a reduced score if desired.

**Comment by somiaj** [comment]
In my limited use of achievements, I thought it might be nice to reduce the number of achievement points in the reduced scoring period. So instead of earning 5 points per correct problem, they only earn 3. I was personally thinking instead of using a percentage reduction, maybe have a configuration field that you can set the number of achievement points correct answers earn during the reducing scoring period. Note I would only reduce the points for the 'per problem earnings', the additional achievements should still earn full points.

**Comment by pstaabp** [comment]
Fixed in #2301
