### ISSUE TITLE
escape button to close feedback

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#2362]
Our disability services team reviewed the new feedback mechanism, and by and large it passes. One request was if the ESC key could be used to close the popover. They figured out how to close it, but described the flow as non-intuitive, and were expecting ESC to close that.

**Comment by drgrice1** [comment]
This is a bad idea.  I also fully believe that that your disability services team is wrong on this.  This kind of keyboard action is this case is what is non-intuitive.  There is a button that you click or press enter when focused to active, and the same to deactivate.  This is how popovers are designed to work.

**Comment by Alex-Jordan** [comment]
Well, they are not "wrong" in any absolute sense; they are firsthand experts in what blind internet users actually experience and what the culture/practice is among assistive technology users browsing the internet. It is not always perfectly aligned with tech standards and tech design principles. If they say it's not intuitive to an actual blind internet user, I would trust them on that. You have to think from the perspective that this popover is the same to most AT users as as a modal dialogue. AT users are not web experts and they don't know that vocabulary, they just now how they are used to navigating with the tools they have. However they did also say that they could work out how to close the popover after ESC didn't work. So it sounds like something that student users can get used to as they are orienting to WeBWorK. I have other changes I need to make to the new student orientation (based on their feedback) and I'll think about explicitly describing how to close the feedback.

**Comment by drgrice1** [comment]
I am not saying that they are wrong in the absolute sense, and that they perhaps had trouble figuring out how to close the popover.  Although, even that seems a little off since there are only a few ways that popovers ever work in any webpage, and this is one of them.  One way that a popover never works in any webpage ever is to close it with the escape key.

**Comment by drgrice1** [comment]
Note that the nicest way to make a popover easily dismissible is the way we usually do popovers for webwork.  That is clicking anywhere else or if the button loses focus.  However, that can't be done in this case because we want accessible users to be able to navigate to MathJax that might be in the popover.

By the way, this is also not a webwork2 issue.  It is a PG issue.  That is where the feedback popovers are created.
