### ISSUE TITLE
Disappearing quiz versions when updating the date for a user.

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#2419]
In short, if the date of a quiz is changed via the "Sets assigned to user" page can remove the versions of that quiz.  This is the RC version of 2.19 -- just updated our production server.  Here's the steps:

1. Create a quiz, assign it to yourself, take the quiz
2. Go to the "Sets assigned to YOU" page (via Accounts Manager) and locate the quiz.  You should also see the version:
<img width="684" alt="image" src="https://github.com/openwebwork/webwork2/assets/879338/a5d0dc17-aa6f-4dfb-87d8-d895b5ed24ee">

3. Change the date on the quiz (not the versioned quiz) and click "Save Changes".
4.  The versioned quiz will disappear:

<img width="654" alt="image" src="https://github.com/openwebwork/webwork2/assets/879338/25c99a34-f729-4b26-910f-013286a1cfe9">

**Comment by stassenm** [comment]
I will add that it is not necessary to change any dates.  It is sufficient for step 3 to be simply "Save Changes." Even with no changes made, all versioned quizzes for that user are deleted.

**Comment by pstaabp** [comment]
Fixed by #2421

**Comment by Alex-Jordan** [comment]
IIRC, I started the redesign of that page and Glenn made it better. I'm sorry if it was my doing!

We've been using the develop branch since late March (or essentially what it was at that time) and had not run into this. Yesterday I applied the patch @drgrice1 made. This morning I have a report of missing quizzes, so naturally at first I thought I messed something up with applying the patch. But it seems clear now that one instructor lost some quizzes a little while ago and only reported it this morning. Testing directly, I am not able to make quizzes get deleted in this manner so I think the patch is definitely working.

**Comment by drgrice1** [comment]
It is as much my fault as yours.  I knew about the importance of the hidden inputs for versioned sets on that page, and that they need to be after the check boxes to work right.  I should have seen this when those changes were made.

Hopefully your instructor did not lose important student quiz data.
