### ISSUE TITLE
Warning shown when using LDAP auth with empty password

### ISSUE THREAD

**Issue by somiaj** [openwebwork/webwork2#2496]
In testing LDAP auth, I tried to enter in no password with a valid account whose password in the data base was NULL (created testing two factor auth with LDAP), and a warning is sent to the user UI. The warning is:

+ AUTH LDAP: bind error 48: The server requires the client which had attempted to bind anonymously or
+ without supplying credentials to provide some form of credentials
+  .

Seems LDAP should just error out and not try to send a blank password to the server in this case.

**Comment by drgrice1** [comment]
Note that this has nothing to do with what webwork has in the database as that is not used in this case.  Only the `passwd` from the submitted form is used for this.  The same happens if you don't enter a password for a user that does have a password saved in the webwork2 database.

Also, this will happen with all versions of webwork.  The code has never considered the case that the password is not given.  Apparently this is something that doesn't happen frequently, and so no one has noticed.

That being said, this is very easy to fix.

**Comment by somiaj** [comment]
Fixed in #2499

**Comment by drgrice1** [comment]
Fixed by #2494.
