### ISSUE TITLE
Fallback password option for classlists

### ISSUE THREAD

**Issue by aweaver1fandm** [openwebwork/webwork2#2540]
This is for WeBWork 2.19

According to instructions found here:
https://webwork.maa.org/wiki/Classlist_Files
If the password field is blank the password should be the student_id

Our instructors added students with the password field blank, as they had done in the past, and the password was not set.
In defaults.config it actually has 
$fallback_password_source = '';
which means none, which is the behavior we saw.

Is the documentation out of date or is defaults.config incorrect?  
For now I changed it in defaults.config to be
$fallback_password_source = 'student_id';

but I know that will get overwritten on an update.  Should I instead add that line to localOverrides.conf or site.conf?

**Comment by Alex-Jordan** [comment]
The documentation is out of date and only applies to 2.18 and earlier.

There is a dropdown menu on the classlist import page. It can be used to specify what you would like the fallback password to be (and the student ID is one option). We do need to update the wiki about this.

Instead of changing `defaults.config`, if you would like to have `$fallback_password_source = 'student_id';` then you shoudl set that in `localOverrides.conf`. Because `defaults.config` is tracked by git.

**Comment by somiaj** [comment]
This was a new feature that was added, here is the commit that added it.

https://github.com/openwebwork/webwork2/commit/8093b83d65573bed53ee95fa2543c8c359776959

The users should be able to select what to use as the password fall back on the input page, but it is defaulting to no fallback. You should override that in `localOverrides.conf`.

**Comment by somiaj** [comment]
The comment has a good description of the changes.

**Comment by aweaver1fandm** [comment]
Thank you.  I will add the change to our localOverrides.

**Comment by aweaver1fandm** [comment]
Issue is resolved

**Comment by dlglin** [comment]
I missed that mention.  It's gone now.
