### ISSUE TITLE
Lack of functionality in problem options (Try/See a Problem and Edit a Problem)

### ISSUE THREAD

**Issue by emcnelis** [openwebwork/webwork2#433]
When working with a problem (this has occurred from within the Library Browser and the Problem Set Details -> Problems environments that I've noticed), clicking on the icons associated with Seeing/Trying a Problem and Editing a Problem do not give the desired action.

Selecting "Seeing/Trying a Problem" icon  -> takes you to a new page, but it seems to vary which page it takes you too; at times I've been taken to the Problem Set Details menu, or to the Library Browser Menu; or to the Import/Export Sets menu -- it seems to be a function of whichever menu I went to most recently (?)

Selecting "Edit a Problem" icon  -> takes me back to a new Library Browser menu again from what I can tell.  

I am able to delete a problem and to rerandomize a problem successfully (as well as add a problem to a homework set from the Library Browser).

**Comment by pstaabp** [comment]
Looking back at this issue. I think this is one more of how we want ww3 to work.  I originally put in the buttons for viewing a problem and editing a problem to mimic that of ww2.  Since ww3 has moved into a single page (with many views) web app, mimicking the functionality of ww2 doesn't make sense in that both of these opened up new tabs.  

A proposal for different paradigm with the "view/try a problem" and "edit a problem" in the library browser is that 
1. View/Try a Problem:  We can create a modal to view the problem as the student would view it and allow the user to try it out.  
2. Edit a Problem.  I think this needs to be a separate view in ww3.  This button could go to that view with a copy of the library problem in the editor.
