### ISSUE TITLE
WW3 Redefines Before And After

### ISSUE THREAD

**Issue by goehle** [openwebwork/webwork2#470]
When I run webwork3/public/dispatch.fcgi I get 
```
Subroutine before redefined at /opt/webwork/webwork2/lib/WeBWorK/Utils.pm line 708.
Subroutine after redefined at /opt/webwork/webwork2/lib/WeBWorK/Utils.pm line 717.
```
I thought we took care of this back in Asheville?

**Comment by pstaabp** [comment]
I'm revisiting this error.  I realize that it comes from adding `use Dancer` to the top of the lib/WeBWorK/Utils.pm file.  I think I did this because somehow I ran into an error that this fixed it.  If I remove this line then I get an error related to a missing Apache::Cookie module, but I'm not running apache1, so it shouldn't need this.     

The missing Apache::Cookie error is tracked this down to a missing environmental variable. In lib/WeBWorK/Cookie.pm there's a switch (depending on apache1 vs. apache2) and if I define `MOD_PERL_API_VERSION=2` then this is all switched. 

This is an easy fix, but will need some checking on different configurations.

**Comment by pstaabp** [comment]
Since it was quiet on our server the past few days, I've been playing with this on our production server. 

If you look at the file change sited above (774fe36), then I just commented out the `use Dancer` line from the WeBWorK::Utils file.  I was able to get this to work on my develop machine in that I run dancer on the command line and was able to set the env var: `MOD_PERL_API_VERSION=2`  which is used to branch on in the WeBWorK::Cookie module.   I thought that explicitly setting this environmental variable would then select the apache2 modules instead of the apache1 modules.  

It appears that I can't get the same results on my production machine which uses the fastcgi scripts from the webwork.apache2.4-config.  It doesn't appear that the variable `MOD_PERL_API_VERSION` isn't being recognized.  Here's the error:

```
[Thu Jun 04 14:51:24.786764 2015] [:warn] [pid 4992] FastCGI: (dynamic) server "/opt/webwork/webwork2/webwork3/public/dispatch.fcgi" started (pid 4998)
Use of uninitialized value $WeBWorK::Constants::WEBWORK_DIRECTORY in concatenation (.) or string at /opt/webwork/webwork2/lib/WeBWorK/Constants.pm line 41.
Unable to read startup script: Can't locate mod_perl.pm in @INC (you may need to install the mod_perl module) (@INC contains: /opt/webwork/pg/lib /opt/webwork/webwork2/lib /opt/webwork/webwork2/webwork3/lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /opt/webwork/webwork2/lib/WeBWorK/Cookie.pm line 35.
BEGIN failed--compilation aborted at /opt/webwork/webwork2/lib/WeBWorK/Cookie.pm line 35.
Compilation failed in require at /opt/webwork/webwork2/lib/WeBWorK/Authen.pm line 54.
BEGIN failed--compilation aborted at /opt/webwork/webwork2/lib/WeBWorK/Authen.pm line 54.
Compilation failed in require at /opt/webwork/webwork2/webwork3/bin/app.pl line 11.
BEGIN failed--compilation aborted at /opt/webwork/webwork2/webwork3/bin/app.pl line 11.
[Thu Jun 04 14:51:25.528966 2015] [:warn] [pid 4992] FastCGI: (dynamic) server "/opt/webwork/webwork2/webwork3/public/dispatch.fcgi" (pid 4998) terminated by calling exit with status '2'
```

I tried to define the variable inside of webwork.apache2.4-config using 
```
$ENV{MOD_PERL_API_VERSION} = 2;
```
but apparently this doesn't work. 

One other thought is that this error is coming from the 
```
use mod_perl;
```
on line 35 of WeBWorK::Cookie.  (But I can get this to work on a standalone dancer, where the environmental variables seem to be passed in.) 

A couple of options here:
1) ignore the warning.  We've been running ww3 for a while now without any apparent ill-effects. 
2) thoughts on why the environmental variables aren't being read in correctly.
