### ISSUE TITLE
CAS authentication breaks on session inactivity timeout

### ISSUE THREAD

**Issue by bldewolf** [openwebwork/webwork2#568]
I'm trying setting up our system to use CAS authentication.  Everything works fine except when a user comes back from an inactive session.  On links where the key is in the path, the user sees a screen that says:

    Your authentication failed. Please try again. Please speak with your instructor if you need help.
    test_course uses an external authentication system. You've authenticated through that system, but aren't allowed to log in to this course.

The user can't actually re-authenticate from this page and has to go back to the home page (or remove the key= GET parameter) to actually re-authenticate and continue using Webwork.

Is there a way to make Webwork handle this automatically?  I looked at CAS.pm but I'm not familiar enough with Webwork internals to see what to change.

**Comment by bldewolf** [comment]
After looking at it again fresh, one solution I found is to change the function so that, if the found key is invalid, to call itself again with the key unset.  I don't think it's the cleanest solution, but it does work.

```diff
--- a/lib/WeBWorK/Authen/CAS.pm
+++ b/lib/WeBWorK/Authen/CAS.pm
@@ -67,7 +67,8 @@ sub get_credentials {
                          defined $Key ? $Key->key : undef, ', user value = ',
                          $self->{session_key});
                        $self->{error} = "Invalid session key";
-                       return 0;
+                       $r->param('key' => undef);
+                       return $self->get_credentials();
                }
                return 1;
                #debug("falling back to superclass get_credentials");
```

**Comment by goehle** [comment]
It does sound like a bug with CAS.  I dont have that kind of authentication service available so its difficult for me to test.  Could you turn on the debug flag in lib/WeBWorK/Constants.pm and post the contents of the debug log here.  In particular I want to see what the debug information is for the get_credientials subroutine you just posted. 

As for your solution, it looks like what that will do is redo the entire CAS authentication.  Its a workaround but not a permanent solution.

**Comment by goehle** [comment]
I've taken a closer look at the code and it looks like the key checking code was put there to prevent people from sneakily getting enrollment data.  But the real key checking should happen in verify_normal_user.  I think what is going on is the students relogin is successful, which changes the session key in the db.  However the parameter key is still floating around and that causes the key check to fail.   In particular the CAS.pm module seems to abuse how the authentication system works since it does password checking in the get_credential methods.  If I knew who wrote the authentication module I would ask how you get the enrollment information and see if there was a better fix.

**Comment by bldewolf** [comment]
It looks like the enrollment information leakage occurs when you change the GET user parameter to another student's username.  If I remove the if statement and they are a student in the course, it gives a message about an expired session.  If they aren't in the course, it gives an authentication error.  So it does seem possible to determine someone's webwork enrollment from their username.

I also tested normal session expiration with the if statement removed.  The user gets stuck on the generic external session expired page, where it says to go back to the external system and enter webwork again (which doesn't really make sense for CAS).

**Comment by goehle** [comment]
Did you remove the whole if statement, or just the first half with the key checking.  The AuthCAS stuff should still be there I think.  Also, what exactly is the expired error.  If its coming from somewhere else in the system then the right thing would be to fix it there, not just have a workaround in one particular authentication module.

**Comment by bldewolf** [comment]
Sorry, I meant the unless statement.  Basically with this diff applied:

```diff
--- a/lib/WeBWorK/Authen/CAS.pm
+++ b/lib/WeBWorK/Authen/CAS.pm
@@ -57,18 +57,6 @@ sub get_credentials {
                $self->{credential_source} = 'params';
                debug("CAS params user '", $self->{user_id},
                  "' key '", $self->{session_key}, "'");
-               # Check session key and user here.  Otherwise, a student can
-               #    determine the enrollment status of any other student if
-               #    they know the userid (which is public information at
-               #    Berkeley).  That would be a privacy violation.
-               my $Key = $r->db->getKey($self->{user_id});
-               unless (defined $Key && $Key->key eq $self->{session_key}) {
-                       debug('undefined or invalid session key:  $Key->key = ',
-                         defined $Key ? $Key->key : undef, ', user value = ',
-                         $self->{session_key});
-                       $self->{error} = "Invalid session key";
-                       return 0;
-               }
                return 1;
                #debug("falling back to superclass get_credentials");
                #return $self->SUPER::get_credentials( @_ );
```

The session expiration page says this message:
>Your session has expired due to inactivity. test_course uses an external authentication system (e.g., Oncourse, CAS, Blackboard, Moodle, Canvas, etc.). Please return to system you used and enter WeBWorK anew.

Since CAS is only really intended to replace the login page, this doesn't quite make sense for it.  It would make more sense to bounce them back to the root course page if their session has expired (if that's safer than leaving them on whatever path they were at).

**Comment by goehle** [comment]
The session expired message will appear for any external authentication system.  If its really a security issue then it can be changed to something more generic like "There was an error with authentication." and that will fix the issue for all external modules. 

As for the authentication, I think the module needs to be refactored so that the actual CAS authentication happens in the proper subroutine, like authenticate or checkPassword.  However, without a working test case it might be a bit.

**Comment by bldewolf** [comment]
For the information leakage: I think the solution needs to be one error message for all errors involving a bad/missing/expired username, session key, etc.  Otherwise you could be telling the client something they shouldn't know.

For the CAS implementation:  I'm not sure authenticate/checkPassword is the right spot.  CAS functions similarly to shibboleth, if you're familiar with that, and that module overrides get_credentials as well.

For now I guess we'll switch back to LDAP.

**Comment by goehle** [comment]
I dont have shibboleth either (we use LDAP).  However it looks like shibboleth takes over get_credentials because it has its own session key and it ignores WeBWorKs session key.  In particular shibboleth forces the session_key parameter to be undefined all the time.   Does CAS have its own session/timeout system?  If so then maybe it should have the same `get_credentials` setup, where it queries the CAS server every time, and if there is a failure it redirects to the appropriate login page.  I.E.  just remove the entire first half of the if statement.

**Comment by goehle** [comment]
Implemented original workaround.
