### ISSUE TITLE
database problem on new install

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#589]
I've been upgrading the software on  my development machine, since almost everything on it was 4+ years old.  I have a new installation nearly running, however when getting up and running I'm adding a new course (the admin one) via the command line with `addcourse admin`  (I know I need to add users too), and when doing this I get the following error:
```
DBD::mysql::db do failed: Specified key was too long; max key length is 1000 bytes at /Library/WebServer/Documents/webwork/webwork2/lib/WeBWorK/DB/Schema/NewSQL/Std.pm line 826.
```
I'm not exactly sure what triggers this (is there a way to get a stack trace on this?) 

I'm installing this on a Mac and just upgraded mysql to version 5.6.24.  This occurs on both the master and develop branches.

**Comment by pstaabp** [comment]
So I went to post this on the webwork forums and saw the error.  Okay I withdraw my post.  

We need to change the line 150 of site.conf.dist
```
$database_storage_engine = 'myisam';
```
to
```
$database_storage_engine = 'innodb';
```

I'm happy to do this.

**Comment by pstaabp** [comment]
Geoff, do you want me to submit this as a pull request?

**Comment by goehle** [comment]
Sure, although I wish I knew more about what was going on.  I've been using myisam for all my installations up to this point and its worked fine.  So its not clear to me what changed.  Which forum post are you talking about, btw?

**Comment by pstaabp** [comment]
Here's the post:

http://webwork.maa.org/moodle/mod/forum/discuss.php?d=3174#p7891

Switching to innodb fixed the problem on the thread and also for me.  This thread is also pointed out in the installation instructions (http://webwork.maa.org/wiki/Installation_Manual_for_2.10_on_Ubuntu_14.04#MySQL_Security_and_Performance_Issuses ) 

It appears that leaving that line in site.conf  is an easier way to set the database type than the mysql settings listed in the documentation.

**Comment by goehle** [comment]
Thanks for the post, that was helpful.  I'm reopening the issue since it seems like there is something to talk about. So its not clear to me that we need to change the default database type in `site.conf.dist`.  This problem appears to be at least two years old and I've done many installations since then which work fine for myisam.  Also, this seems to be a problem only for those people who change the default mysql character encoding to utf8 since utf8 characters take more bytes.  We have a few options. 
-  Change the default database type.  There seem to be performance bonuses to myisam on some systems, and the default character set for mysql is latin1, not utf8 so in general myisam should work.  
-  Do nothing.  We could add documentation to `site.conf.dist` describing the difference between the two.  Say something like myisam tends to be faster but is incompatible with utf8.  However, it would be up to admins to figure out what combination of character set/database type is up to them.  
- On the other other hand we could acutally do what Danny suggested in the thread and change the index to only look at the first 100 characters of a key field.  This would involve changing the line: https://github.com/openwebwork/webwork2/blob/master/lib/WeBWorK/DB/Schema/NewSQL/Std.pm#L149  I dont actually know all of the ramifications of this.  In theory it should be fine since 100 characters is plenty for a set/user name.

**Comment by taniwallach** [comment]
I ran into this thread when searching for something about the DB table type with UTF8 support... The comment that UTF8 support and MyISAM tables do not work together in WW in no longer accurate.

WW 2.15 with `utf8mb4` in use is working fine with MyISAM tables. The lengths of some database fields were reduced (as part of the UTF-8 changes to 2.15) to avoid going over the key length limit of 1000 bytes for MyISAM tables.
See: https://github.com/openwebwork/webwork2/commit/b840e28f802dd69f6251aa4c4096bcca43c2ad90
