### ISSUE TITLE
math4 theme messes with image dimensions

### ISSUE THREAD

**Issue by jwj61** [openwebwork/webwork2#616]
If you have an image, say created with on the fly graphics, you can set the height and width of the image on the pg side using image.  One can verify that the correct html tag is generated.

When viewed in math3, these dimensions are respected, but in math4 the image is square, which throws off the aspect ratio if the author did not intend it to be square.

I just added Library/ASU-topics/setSets/venn2circ.pg which has a Venn diagram.  The circles are circles in math3, but not in math4.

**Comment by goehle** [comment]
After tracking this down I've found its caused by the bootstrap responsive code for handling images.  Basically it scales images down so it doesn't overflow the window.  However, it seems that the scaling is done according to the images inherent dimensions.  The image in the problem you gave me is natively 400x400 so when the browser scales the image it scales it as a square.  So its not that math4 is forcing images to be square, its more that your image is square and math4 is overriding your attempts to rescale it.  

There are two sides to this.  From what I can tell poking around stack exchange, the "right" thing to do is make sure that your image is generated with the desired aspect ratio.  If you use the browser to scale it to square then clicking "view image" will show you the original unsquare version.  Also, if we remove this particular bootstrap code then images won't scale down on small screens, which is a bit of a shame.  On the other hand, if it breaks a lot of OPL problems then it needs to be changed.  I don't know the extent of the issue, and I'm also not sure how hard we should fight to preserve the auto-scaling properties of bootstrap.  

Cheers.
Geoff.

**Comment by jwj61** [comment]
How much it affects existing OPL problems would depend on how many set "size" when creating the graph, as opposed to relying on setting the range of x and y values.  I imagine they are somewhat split.

**Comment by goehle** [comment]
Could we the grapher so that if a range of x and y values are set, it creates an image with the same aspect ratio  (assuming that size isn't also set)?

**Comment by jwj61** [comment]
I think we could do that, but it doesn't change the other aspect.  Namely that the image macro lets the problem author explicitly set the dimensions of the image, and then we are sometimes not honoring that, and perhaps worse, that the result is theme dependent.

**Comment by goehle** [comment]
That's true.  I think it comes down to how we want to support small screens.  If we always honor the dimensions then the image won't be responsive.  I've seen a lot of  students using WeBWorK on tablets/phones so I think trying for more responsive design is worth it.  

One option is to add extra javascript which rescales images based on their height and width attributes, rather than letting the browser doing the resizing.  This is probably not as robust as letting the browser do the work, and it enables "improper" html.  However, its one way to get both responsive design and allow instructors to use the height and width parameters they way they have been.
