### ISSUE TITLE
Switch to email sender with free license?

### ISSUE THREAD

**Issue by d-torrance** [openwebwork/webwork2#655]
I'm currently working on packaging some of WeBWorK's perl dependencies for Debian, with the long-term goal of getting WeBWorK itself into Debian.

One of the dependencies, Mail::Sender, was removed from the main Debian archive due to its non-free license [1].  This would prevent a future WeBWorK package from being included in the main archive as well, as all dependencies must be in main.

Would there be any interest in switching to another perl module with the same functionality but with a free license?  In the linked bug, Email::Send and Email::Sender are both suggested as alternatives.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=568652

**Comment by goehle** [comment]
It looks like Mail::Sender is "non-free" because it includes the clause
```
This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself. There is only one additional condition, you may NOT use this module for SPAMing! NEVER!
```
While I appreciate the distinction being made in that bug report (e.g. placing any restrictions on your package, even one involving spam, makes it non-free), I'm not sure I find it particularly compelling.  

On the other hand if you get your debian package to the point where this is one of only a few issues keeping it from being completed then I think that would be a real argument to move over to a different package.  After we get 2.11 released I'll take a closer look at what a changeover would involve.  Mail::Sender is only used in three (?) places so it might not be too bad.

**Comment by d-torrance** [comment]
Sounds good -- thanks!  I'll keep you updated on progress of the Debian package.
