### ISSUE TITLE
Install script failed

### ISSUE THREAD

**Issue by obref** [openwebwork/webwork2#701]
Got it, I'll download the OPL from
https://github.com/openwebwork/webwork-open-problem-library.git.
Running [/usr/bin/git clone
https://github.com/openwebwork/webwork2.git]...
Cloning into 'webwork2'...
fatal: unable to access 'https://github.com/openwebwork/webwork2.git/':
GnuTLS recv error (-9): A TLS packet with unexpected length was
received.
Warning! The last command exited with an error: '/usr/bin/git clone
https://github.com/openwebwork/webwork2.git' exited with value 128

We have logged the error message, if any. We suggest that you exit now
and report the error at https://github.com/openwebwork/ww_install

**Comment by goehle** [comment]
This is an issue with git.  

I found a bug report about it:  https://bugs.launchpad.net/ubuntu/+source/gnutls26/+bug/1111882 However that bug report is pretty old so it might be something else.  I've also seen this pop up as a ssl certification validation issue:  https://github.com/PeerioTechnologies/peerio-client/issues/329  That case was fixed by installing the package ca-certificates.  In general it seems like an ssl configuration thing.  You'll need to mess with things until you can successfully run the following command from the command line.  
```
git clone https://github.com/openwebwork/webwork2.git
```
If you cant get that working a final option would be to try and avoid the ssl altogether.  When the ww_install script asks where you want to download webwork from enter the same command without the https.  Then do the same thing for pg.  You might still run into trouble when it tries to download MathJax and the OPL, though.
