### ISSUE TITLE
Maketext error

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#713]
I just pulled in develop (both ww and pg) and in all problems, getting the following error:

```
Error in maketexting "You have [negquant,_1,unlimited attempts,attempt,attempts] remaining.": Can't locate object method "negquant" via package "WeBWorK::Localize::I18N::en" in bracket code [compiled line 2], as used at /Library/Webserver/Documents/webwork/webwork2/lib/WeBWorK/Localize.pm line 55.
```

**Comment by goehle** [comment]
WeBWorK's custom version of Localize isn't getting set up properly.  The function its looking for is at

https://github.com/openwebwork/webwork2/blob/master/lib/WeBWorK/Localize.pm#L67

**Comment by goehle** [comment]
Its possible that this is more safe compartment wierdness.  Mikes code at https://github.com/openwebwork/webwork2/pull/705/files#diff-90164f182c4585ebda6417d788967684R174 allows the safe compartment to access getLoc.  However, its not 100% clear to me that you can then use getLoc, because its going to try and call `WeBWorK::Localize::I18N` which may not be available to the safe compartment.

**Comment by pstaabp** [comment]
I just noticed that this error only occurs for open problems.

**Comment by pstaabp** [comment]
This was on my branch, so closing this issue.
