### ISSUE TITLE
student hardcopy differs if made by student versus professor

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/webwork2#757]
If I create the pdf for a student, the beginproblem() text includes the file path to the file. If a student created their own pdf, the file path is omitted. I think better behavior would be for the outputs to match. I would only create a student's hard copy if I wanted to give it to a student, and the file paths are distractions. Am I missing a use for hardcopy where the file path should be there?

**Comment by mgage** [comment]
There is a possible use for the path.  From time to time I have made paper copies of subsets of the library or of all of the homework sets in a course in order to organize the next version of the course or to reorganize the library.  What happens if you print the hardcopy when acting as a student? That's probably what you would do if you were printing out a copy for a student.  Perhaps we can make the view of the path depend on the targeted user (effective user) for the question instead of the actual user.

**Comment by Alex-Jordan** [comment]
I might want to print out all 30 student's sets to hand out during one class (say if I was using WeBWorK to generate some kind of in-class quiz or activity.) Then I wouldn't want to act as each one. I'd want to highlight all the students while just acting as myself. To do the organizational things you mention, would it be enough to print out versions for yourself (or any of the professors in the course)?

I was thinking along the lines of what you say at the end. That the behavior would be based on who that version of the set has been assigned to instead of who is generating the pdf.

**Comment by mgage** [comment]
The orginizational stuff I have in mind could be accomplished with just professor s.

What I'm thinking of at the moment is to have the path printed out according to the user for html and according to the targeted user for the problem when creating hardcopy output


On Jun 24, 2017 3:02 PM, Alex Jordan <notifications@github.com> wrote:

I might want to print out all 30 student's sets to hand out during one class (say if I was using WeBWorK to generate some kind of in-class quiz or activity.) Then I wouldn't want to act as each one. I'd want to highlight all the students while just acting as myself. To do the organizational things you mention, would it be enough to print out versions for yourself (or any of the professors in the course)?

I was thinking along the lines of what you say at the end. That the behavior would be based on who that version of the set has been assigned to instead of who is generating the pdf.

**Comment by Alex-Jordan** [comment]
This touches on #1239 and the extended enhancements Glenn has made. I suspect this issue can be closed once #1239 is merged.

**Comment by drgrice1** [comment]
I think this can be closed now.  Please re-open if I am mistaken.
