### ISSUE TITLE
Creating a new version of a problem does not copy images

### ISSUE THREAD

**Issue by heiderich** [openwebwork/webwork2#763]
As a professor, when viewing a problem in a problem set and clicking Edit2 to create a new version of a problem that contains images, these images are not copied to the local folder of that course. Consequently the images are not shown. Am I doing something wrong or should this be considered a bug?

**Comment by mgage** [comment]
This is known behavior.  I consider it a bug, but it's been unresolved for a long time. One can work around it by using the FileManager, but it is still a bug.

**Comment by heiderich** [comment]
Let me add that also local .pl files that are loaded via loadMacros() are not copied automatically.

**Comment by Alex-Jordan** [comment]
I believe this is at least partly addressed at this point in time. Please re-open if I'm wrong.

I just checked on the develop branch, opening a problem file in the editor. The problem file had an adjacent image file. (The problem file uses this image file, but that won't be relevant.) I saved as a new file in a completely new folder, and then the new folder contained a copy of the image file.

I think this behavior can be overkill, since it copies adjacent files to to the problem file regardless of whether that problem actually uses those assets. But I think it is enough to close this issue.
