### ISSUE TITLE
Hardcopy error message for pdflatex automatically fixed issues

### ISSUE THREAD

**Issue by andrew-gardener** [openwebwork/webwork2#870]
I might be missing some context but I believe that it might be a good idea to lower the severity of the message that's displayed (or maybe completely ignore it) when pdflatex runs into issues that it automatically fixes and that don't cause issues with the generated pdf.

for example running into:
```
! Missing $ inserted.
<inserted text> 
                $
l.90 ...{\bf  Period } \\  1 &  \[9 + 16 sin(4 \pi
                                                   t + \frac{\pi}{2})\] &  [...
I've inserted a begin-math/end-math symbol since I think
you left one out. Proceed, with fingers crossed.
```

will make the Hardcopy look like it failed to generate to some users (even though they can still download the Hardcopy, it is not predominate).

**Comment by andrew-gardener** [comment]
Here is an example problem that will cause latex issues when generating the pdf but will still produce a pdf
```
DOCUMENT();

loadMacros(
	"PGstandard.pl",     # Standard macros for PG language
	"MathObjects.pl",
	"PGML.pl",
	"parserPopUp.pl",
	"parserMultiAnswer.pl",
	"parserRadioButtons.pl",
	"PGauxiliaryFunctions.pl",
	"niceTables.pl"
);

Context("Numeric");
Context()->strings->add(NA=>{});

$alpha_0 = random(2, 15, 1);
$beta_0 = random(10, 20, 1);
$a_0 = random(2, 5, 1);
$b_0 = random(2, 5, 1);

$mcPeriodic = PopUp(["?","Periodic","Aperiodic"], "Periodic");
$ans1 = 2/$a_0;
$ans1 = Formula("$ans1");

Context()->flags->set(tolerance=>.01, tolType => 'absolute');

BEGIN_TEXT
Determine whether or not each of the signals below are periodic or aperiodic. If the signal is periodic, find its period. Else, answer "NA".

$PAR
\{
	DataTable(
		[
			['','$BBOLD Signal $EBOLD','$BBOLD Periodic/Aperiodic $EBOLD','$BBOLD Period $EBOLD'],
			['1','\[$alpha_0 + $beta_0 sin($a_0 \pi t + \frac{\pi}{$b_0})\]',$mcPeriodic->menu(),ans_rule(10)]
		],
		center => 0,
		allcellcss=>'padding-left:20px; padding-right:20px; border: solid thin #CCCCCC;',
	);
\}
END_TEXT

ANS($mcPeriodic->cmp);
ANS($ans1->cmp);

ENDDOCUMENT();
```

**Comment by dpvc** [comment]
> I believe that it might be a good idea to lower the severity of the message that's displayed (or maybe completely ignore it) when pdflatex runs into issues that it automatically fixes 

I disagree.  The error message is there to inform you that there is a problem with the LaTeX in the problem (and there is in this case), and there is no guarantee that the automatic fix is correct (and in this case, it isn't).  Note that in this problem the dollar sign is inserted just before the `\pi` (and another one is inserted at the end of the table cell to balance it during a later error message).  But math mode needs to be started at the beginning of the cell, not just before the `\pi`; without that, the spacing around the plus sign will be wrong, for example.  (Also, the `sin` should be `\sin` in order to get the font and spacing correct.)

So removing (or downplaying) the message is a bad idea, because it would prevent the problem author from realizing that there is an issue that needs to be fixed.

The real issue is that the author is trying to use display-mode math inside the table cell, which is not allowed.  The `\[...\]` should be replaced by `\(...\)`.  If the display mode is to force the fraction to be in display mode, one could switch to `\dfrac` rather than `\frac`, or use `\(\displaystyle ... \)` instead.

So in my opinion, the solution to having the error message is to fix the LaTeX in the problem to be error free, rather than throwing away the error message.  In my experience LaTeX's automate fixes are rarely effective, and should not be relied upon.
