### ISSUE TITLE
Gateway Quiz with non-consecutively numbered problems

### ISSUE THREAD

**Issue by heiderich** [openwebwork/webwork2#899]
It seems that when a homework set of type "gateway quiz" with questions numbered in a non-consecutive way is taken by a student, they may get the following error:

"The selected problem set (`name of homework set`) is not a valid set for `user`:
One or more of the problems in this set have not been assigned to you."

This was already reported in the forum by @Alex-Jordan (http://webwork.maa.org/moodle/mod/forum/discuss.php?d=3134), but I could not find a bug report for it and I am still experiencing this with WeBWorK 2.13.

**Comment by mikeshulman** [comment]
I ran into this error and would like to help fix the problem.  The forum discussion suggests that the underlying bug may be unfixable without a database redesign.  Is that really true?  Looking at the code that produces that error in `ContentGenerator/GatewayQuiz.pm` my guess is that what's happening is that `@problemNumbers` is a list of the problem numbers appearing in the quiz, and the code assumes that these are sequential from 1 so that subtracting 1 from a problem number yields the 0-based index `$pIndex` of the problem.  But couldn't one just iterate through the indices directly, like in 5873fce1d79?  I don't know whether such a change would necessitate other changes elsewhere, but I just tested it very briefly on my installation and it seemed to work.

**Comment by drgrice1** [comment]
mikeshulman:  This does seem to fix the problem.  I have tested it, and it works well.  Analyzing the code as it currently is, it seems that it was a mistake to decrement the problem number to achieve zero based indexing.

I would recommend that you drop the `my $problemNumber = $sortedProblemNumbers[$pIndex];` line, and just assign `$sortedProblemNumbers[$pIndex]` directly to `$pg` on line 1165.

You should put a pull request in for this.

**Comment by drgrice1** [comment]
So looking at this a bit closer, it seems that the actual problem number isn't even needed.  Currently the `$pg` variable is set to the problem number, and that is pushed onto the `@pg_results array`, and then `$self->{ra_pg_results}` is set as a reference to that array.  Looking at the usage of the `ra_pg_results` key of that hash throughout the file, I see that the problem number is not actually used anywhere.  All that is important is the value of that entry in the array **not** be a reference.  So it could be set to 0, and it will work.  The only problem is decrementing the `$pIndex` variable.

**Comment by mikeshulman** [comment]
Thanks for looking at this!  Would you like the pull request to do what you suggest in the second comment and not even bother to sort the array?

**Comment by drgrice1** [comment]
You might look through the file too, and see if you see any place where the problem number stored in that hash is actually used.  If not then sorting the array of problem numbers is unnecessary and inefficient.

**Comment by drgrice1** [comment]
I went through the file one more time just to make sure, and double checked a few places to be certain.  It really is not used.  So the sorting should be removed.  Just iterate `$pIndex` from 0 to `$#problemNumbers` and assign 0 to `$pg` on line 1165.

**Comment by drgrice1** [comment]
At some point that file needs to be massively cleaned up.  It is a pain reading code in that file due to horrible indentation practices and commented out old code that should be removed.

**Comment by mikeshulman** [comment]
Yeah, you said it.

**Comment by drgrice1** [comment]
This should be fixed with pr #1128.

**Comment by Alex-Jordan** [comment]
This was fixed by #1128 and #1197.
