### ISSUE TITLE
warning with WWclient.pm

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork2#925]
On line 107 of [WWclient.pm]() we use the package `Crypt::SSLeay`.  I'm not able to load it on MacOS, there's some build issues, but I'm not sure this is needed anymore. Here a link to the [Crypt::SSLeay documentation](https://metacpan.org/pod/Crypt::SSLeay#DO-YOU-NEED-Crypt::SSLeay)

My "patch" is to comment that out and everything runs (but I'm not doing https on my development machine, it's just a local server.)

**Comment by mgage** [comment]
Crypt::SSLeay has been deprecated.  I think it can be replaced by using
LWP::Protocol::https

see note at: 
https://metacpan.org/pod/Crypt::SSLeay
----------------------------------------------------------------------------
DO YOU NEED Crypt::SSLeay?
Starting with version 6.02 of LWP, https support was unbundled into LWP::Protocol::https. This module specifies as one of its prerequisites IO::Socket::SSL which is automatically used by LWP::UserAgent unless this preference is overridden separately. IO::Socket::SSL is a more complete implementation, and, crucially, it allows hostname verification. Crypt::SSLeay does not support this. At this point, Crypt::SSLeay is maintained to support existing software that already depends on it. However, it is possible that your software does not really depend on Crypt::SSLeay, only on the ability of LWP::UserAgent class to communicate with sites over SSL/TLS.

If are using version LWP 6.02 or later, and therefore have installed LWP::Protocol::https and its dependencies, and do not explicitly use Net::SSL before loading LWP::UserAgent, or override the default socket class, you are probably using IO::Socket::SSL and do not really need Crypt::SSLeay.

If you have both Crypt::SSLeay and IO::Socket::SSL installed, and would like to force LWP::UserAgent to use Crypt::SSLeay, you can use:
-------------------------------------------------------------------
Crypt::SSLeay appears as "use Crypt::SSLeay;" in a number of files, sometimes even when it is not being used.  It definitely not needed if you are using http: instead of https:. 

I just haven't gotten around to tracking down all of the instances of Crypt::SSLeay and replacing them with LWP::Protocol::https when necessary and then checking that everything still works.
