### ISSUE TITLE
project to update develop  PDF generation for languages such as Hebrew, Chinese, etc.

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#943]
* PDF generation with Hebrew question. 
    * The LaTeX headers will needs more configuration work, and additional LaTeX packages and fonts will need to be installed.
    * This sort of issue will apply to any language which requires additional LaTeX packages and/or fonts.
    * For Hebrew, Arabic, etc - the need to swap between RTL and LTR text directions make the matter even more complex.

**Comment by taniwallach** [comment]
https://github.com/openwebwork/webwork2/pull/972 provides initial support for PDF generation using xelatex, polyglossia, and fontspec.  Polyglossia supports 75+ languages and uses TTF/OTF fonts in a native manner.

See:
  - https://ctan.org/tex-archive/macros/xetex/latex/polyglossia/
  - https://github.com/reutenauer/polyglossia/

The PR includes enough additions to the Docker config to get Hebrew+English files to compile. Sample header files for xelatex, polyglossia, and fontspec were provided in addition to the Hebrew one which also needs the `bidi` package.

To support additional languages which polyglossia supports should be pretty easy, but additional TTF/OTF fonts must be installed, and customized hardcopy themes need to be made for each language/language combination.

Adding xelatex text direction switching commands to the Hebrew PG problems using the `openSpan()` and `openDiv()` macros so that the additional necessary LaTeX command  get into the generated latex files is another task, but was not hard to do on some small examples.

**Comment by Alex-Jordan** [comment]
Closing this. I think that with the current hardcopy theme structure, plus the ability to set `xelatex` as the latex engine, you can handle languages with non-latin characters now. Can reopen if this is confirmed to not be true.
